const data = [
  { gapoktan: "Lumintu", namaKelompok: "Karya Makmur", desa: "Wonosari" },
  { gapoktan: "Lumintu", namaKelompok: "Tani Karya", desa: "Wonosari" },
  { gapoktan: "Lumintu", namaKelompok: "Tani Maju", desa: "Wonosari" },
  { gapoktan: "Tani Harapan", namaKelompok: "Sri Rahayu", desa: "Pandansari" },
  { gapoktan: "Tani Harapan", namaKelompok: "Sri Sadono", desa: "Pandansari" },
  { gapoktan: "Tani Harapan", namaKelompok: "SriMukti", desa: "Pandansari" },
  { gapoktan: "Tani Makmur", namaKelompok: "Marsudi Luhur", desa: "Girikerto" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sido Luhur", desa: "Girikerto" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sido Mukti", desa: "Girikerto" },
  { gapoktan: "Dewi Sri", namaKelompok: "Sri Jaya", desa: "Ngrendeng" },
  { gapoktan: "Dewi Sri", namaKelompok: "Sri Mulyo", desa: "Ngrendeng" },
  { gapoktan: "Dewi Sri", namaKelompok: "Sri Handayani", desa: "Ngrendeng" },
  { gapoktan: "Dewi Sri", namaKelompok: "Sri Rejeki", desa: "Ngrendeng" },
  { gapoktan: "Argo Makmur", namaKelompok: "Tani Mulyo", desa: "Hargosari" },
  { gapoktan: "Argo Makmur", namaKelompok: "Sumber Rejeki", desa: "Hargosari" },
  { gapoktan: "Argo Makmur", namaKelompok: "Sri Makmur", desa: "Hargosari" },
  { gapoktan: "Argo Makmur", namaKelompok: "Sri Rejeki", desa: "Hargosari" },
  { gapoktan: "Argo Makmur", namaKelompok: "Panca Karya", desa: "Hargosari" },
  { gapoktan: "Sinar Jaya", namaKelompok: "Tani Makmur", desa: "Pocol" },
  { gapoktan: "Sinar Jaya", namaKelompok: "Tani Mulyo", desa: "Pocol" },
  { gapoktan: "Sinar Jaya", namaKelompok: "Tani Rukun", desa: "Pocol" },
  { gapoktan: "Sinar Jaya", namaKelompok: "Tani Widodo", desa: "Pocol" },
  { gapoktan: "Gemilang", namaKelompok: "Sri Mulyo", desa: "Gendol" },
  { gapoktan: "Gemilang", namaKelompok: "Sri Mulyo 1", desa: "Gendol" },
  { gapoktan: "Gemilang", namaKelompok: "Sri Mulyo 2", desa: "Gendol" },
  { gapoktan: "Gemilang", namaKelompok: "Sri Rejeki", desa: "Gendol" },
  { gapoktan: "Lintang Sadane", namaKelompok: "Sumber Makmur", desa: "Sine" },
  { gapoktan: "Lintang Sadane", namaKelompok: "Sri Sadani", desa: "Sine" },
  { gapoktan: "Lintang Sadane", namaKelompok: "Sri Widodo", desa: "Sine" },
  { gapoktan: "Lintang Sadane", namaKelompok: "Sri Makmur", desa: "Sine" },
  { gapoktan: "Lintang Sadane", namaKelompok: "Tani mulyo", desa: "Sine" },
  { gapoktan: "Sumber Barokah", namaKelompok: "Sri Rejeki 1", desa: "Sumberejo" },
  { gapoktan: "Sumber Barokah", namaKelompok: "Sri Rejeki 2", desa: "Sumberejo" },
  { gapoktan: "Sumber Barokah", namaKelompok: "Sido Luhur", desa: "Sumberejo" },
  { gapoktan: "Sumber Barokah", namaKelompok: "Makmur Selalu", desa: "Sumberejo" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sido Rukun", desa: "Sumbersari" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Makmur", desa: "Sumbersari" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sri Widodo", desa: "Sumbersari" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Tentrem", desa: "Sumbersari" },
  { gapoktan: "Baroto", namaKelompok: "Sri Makmur", desa: "Kuniran" },
  { gapoktan: "Baroto", namaKelompok: "Sedyo Rahayu", desa: "Kuniran" },
  { gapoktan: "Baroto", namaKelompok: "Sri Rejeki", desa: "Kuniran" },
  { gapoktan: "Baroto", namaKelompok: "Sri Rahayu", desa: "Kuniran" },
  { gapoktan: "Baroto", namaKelompok: "Tani Mukti", desa: "Kuniran" },
  { gapoktan: "Karya Makmur", namaKelompok: "Darmo Martani", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Usaha Tani", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Harapan", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Bakti Rahayu", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Makmur Selalu", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Sejahtera", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Maju", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Makmur Tani", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Tukul", desa: "Tulakan" },
  { gapoktan: "Andalas", namaKelompok: "Tentrem Rahayu", desa: "Ketanggung" },
  { gapoktan: "Andalas", namaKelompok: "Makmur Bertani", desa: "Ketanggung" },
  { gapoktan: "Andalas", namaKelompok: "Martani Mulyo", desa: "Ketanggung" },
  { gapoktan: "Catur Manunggal", namaKelompok: "Mardi Rahayu", desa: "Jagir" },
  { gapoktan: "Catur Manunggal", namaKelompok: "Tani Karya", desa: "Jagir" },
  { gapoktan: "Catur Manunggal", namaKelompok: "Sri Rejeki", desa: "Jagir" },
  { gapoktan: "Catur Manunggal", namaKelompok: "Sri Rahayu", desa: "Jagir" },
  { gapoktan: "Sinar Bahagia", namaKelompok: "Sri Makmur", desa: "Kauman" },
  { gapoktan: "Sinar Bahagia", namaKelompok: "Tani Subur", desa: "Kauman" },
  { gapoktan: "Sinar Bahagia", namaKelompok: "Tani Bahagia", desa: "Kauman" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Sri Makmur I", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Sri Makmur II", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Dadi Mulyo", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Hargo Makmur", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Sri Rahayu", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Hargo Lestari", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Sido dadi", desa: "Hargomulyo" },
  { gapoktan: "Tani Lestari", namaKelompok: "Sido Makmur", desa: "Giriharjo" },
  { gapoktan: "Tani Lestari", namaKelompok: "Sido Rukun", desa: "Giriharjo" },
  { gapoktan: "Tani Lestari", namaKelompok: "Sido Mukti", desa: "Giriharjo" },
  { gapoktan: "Tani Lestari", namaKelompok: "Sido Maju", desa: "Giriharjo" },
  { gapoktan: "Tani Lestari", namaKelompok: "Giri Wono", desa: "Giriharjo" },
  { gapoktan: "Ngudi Roso", namaKelompok: "Tani Mulyo", desa: "Setono" },
  { gapoktan: "Ngudi Roso", namaKelompok: "Lawu Indah", desa: "Setono" },
  { gapoktan: "Ngudi Roso", namaKelompok: "Lawu Makmur", desa: "Setono" },
  { gapoktan: "Ngudi Roso", namaKelompok: "Sri Mulyo", desa: "Setono" },
  { gapoktan: "Ngudi Roso", namaKelompok: "Sri Sadono", desa: "Setono" },
  { gapoktan: "Margo Manunggal", namaKelompok: "Margo Rahayu", desa: "Wakah" },
  { gapoktan: "Margo Manunggal", namaKelompok: "Margo Rukun", desa: "Wakah" },
  { gapoktan: "Margo Manunggal", namaKelompok: "Gemah Ripah I", desa: "Wakah" },
  { gapoktan: "Margo Manunggal", namaKelompok: "Gemah Ripah II", desa: "Wakah" },
  { gapoktan: "Margo Manunggal", namaKelompok: "Sumber Rejeki", desa: "Wakah" },
  { gapoktan: "Manunggal Karso", namaKelompok: "Arum Dalu", desa: "Tawangrejo" },
  { gapoktan: "Manunggal Karso", namaKelompok: "Sri Rejeki", desa: "Tawangrejo" },
  { gapoktan: "Manunggal Karso", namaKelompok: "Sri Sadono", desa: "Tawangrejo" },
  { gapoktan: "Manunggal Karso", namaKelompok: "Tawang Sari", desa: "Tawangrejo" },
  { gapoktan: "Suka Mulya", namaKelompok: "Setia Kawan", desa: "Sambirejo" },
  { gapoktan: "Suka Mulya", namaKelompok: "Ngudi Tani", desa: "Sambirejo" },
  { gapoktan: "Suka Mulya", namaKelompok: "Margo Kencono", desa: "Sambirejo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Karya Tani", desa: "Manisharjo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Sri Mulih", desa: "Manisharjo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Konco Tani", desa: "Manisharjo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Karya Utama", desa: "Manisharjo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Ngudi Makmur", desa: "Manisharjo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Subur Makmur", desa: "Manisharjo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Tirta Nirwala", desa: "Sidomulyo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Widu Satrio", desa: "Sidomulyo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Sadewo", desa: "Sidomulyo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Nakulo", desa: "Sidomulyo" },
  { gapoktan: "Sekar Lawu", namaKelompok: "Ngesti Rejeki", desa: "Ngrambe" },
  { gapoktan: "Sekar Lawu", namaKelompok: "Sempulur", desa: "Ngrambe" },
  { gapoktan: "Sekar Lawu", namaKelompok: "Ngesti Tani", desa: "Ngrambe" },
  { gapoktan: "Sekar Lawu", namaKelompok: "Ngesti Lestari", desa: "Ngrambe" },
  { gapoktan: "Sekar Lawu", namaKelompok: "Beran Makmur", desa: "Ngrambe" },
  { gapoktan: "Ardi Lawu", namaKelompok: "Sri Lestari", desa: "Babadan" },
  { gapoktan: "Ardi Lawu", namaKelompok: "Sri Widodo", desa: "Babadan" },
  { gapoktan: "Ardi Lawu", namaKelompok: "Sri Rejeki", desa: "Babadan" },
  { gapoktan: "Ardi Lawu", namaKelompok: "Mekar Tani", desa: "Babadan" },
  { gapoktan: "Ardi Lawu", namaKelompok: "Budi Luhur", desa: "Babadan" },
  { gapoktan: "Ngudi Tani", namaKelompok: "Sedyo Makmur", desa: "Krandegan" },
  { gapoktan: "Ngudi Tani", namaKelompok: "Kondang Makmur", desa: "Krandegan" },
  { gapoktan: "Ngudi Tani", namaKelompok: "Jati Lestari", desa: "Krandegan" },
  { gapoktan: "Ngudi Tani", namaKelompok: "Tani Makmur", desa: "Krandegan" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Tani Mulyo", desa: "Pucangan" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Among Tani", desa: "Pucangan" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Mekarsari", desa: "Pucangan" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Sri Rejeki", desa: "Pucangan" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Margo Rejeki", desa: "Pucangan" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Rejeki Tani", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Dewi Sri I", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Dewi Sri II", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Dewi Sri III", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Margo Mulyo", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Tani Mulyo", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Tani Manunggal", desa: "Cepoko" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Rukun Santoso II", desa: "Mendiro" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Rukun Santoso", desa: "Mendiro" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Ngudi Mulyo", desa: "Mendiro" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Suko Raharjo", desa: "Mendiro" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Sedyo Makmur 1", desa: "Mendiro" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Sedyo Makmur 2", desa: "Mendiro" },
  { gapoktan: "Umbul Mandiri", namaKelompok: "Sendang Kinasih", desa: "Umbulrejo" },
  { gapoktan: "Umbul Mandiri", namaKelompok: "Sendang Minulyo", desa: "Umbulrejo" },
  { gapoktan: "Mitra Tani", namaKelompok: "Pamardisiwi", desa: "Kletekan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Lawu Subur", desa: "Kletekan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Ngudi Rahayu", desa: "Kletekan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Ngudi Utomo", desa: "Kletekan" },
  { gapoktan: "Jati Makmur", namaKelompok: "Arum Sari", desa: "Jaten" },
  { gapoktan: "Jati Makmur", namaKelompok: "Retno Mekar", desa: "Jaten" },
  { gapoktan: "Jati Makmur", namaKelompok: "Margo Tani", desa: "Jaten" },
  { gapoktan: "Jati Makmur", namaKelompok: "Citrun Jaya", desa: "Jaten" },
  { gapoktan: "Giri Bangkit", namaKelompok: "Rukun Tani", desa: "Girimulyo" },
  { gapoktan: "Giri Bangkit", namaKelompok: "Pamardi Tiwi", desa: "Girimulyo" },
  { gapoktan: "Giri Bangkit", namaKelompok: "Mulyo Rahayu", desa: "Girimulyo" },
  { gapoktan: "Giri Bangkit", namaKelompok: "Sido mulyo", desa: "Girimulyo" },
  { gapoktan: "Giri Bangkit", namaKelompok: "Sekar Asih", desa: "Girimulyo" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Budi Kamulyan", desa: "Ngrayudan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Jamandiri Kencana", desa: "Ngrayudan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sri Mulyo", desa: "Ngrayudan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sri Widodo", desa: "Ngrayudan" },
  { gapoktan: "Garuda Merah", namaKelompok: "Sri Rejeki", desa: "Talang" },
  { gapoktan: "Garuda Merah", namaKelompok: "Sri Dadi", desa: "Talang" },
  { gapoktan: "Wahyu Risqi", namaKelompok: "Sri Asih", desa: "Macanan" },
  { gapoktan: "Wahyu Risqi", namaKelompok: "Pondok Makmur", desa: "Macanan" },
  { gapoktan: "Wahyu Risqi", namaKelompok: "Setyo Asih", desa: "Macanan" },
  { gapoktan: "Wahyu Risqi", namaKelompok: "Sendang Kamulyan", desa: "Macanan" },
  { gapoktan: "Sido Arum", namaKelompok: "Sido Makmur", desa: "Brubuh" },
  { gapoktan: "Sido Arum", namaKelompok: "Arum Dina", desa: "Brubuh" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Sido Makmur", desa: "Jogorogo" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Tani Subur", desa: "Jogorogo" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Tani Rahayu", desa: "Jogorogo" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Enggal Makmur", desa: "Jogorogo" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Sendang Makmur", desa: "Jogorogo" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Sekar Makmur", desa: "Jogorogo" },
  { gapoktan: "Tani Bersatu", namaKelompok: "Ngudi Mulyo", desa: "Dawung" },
  { gapoktan: "Tani Bersatu", namaKelompok: "Ngudi Rejeki", desa: "Dawung" },
  { gapoktan: "Tani Bersatu", namaKelompok: "Ngudi Rahayu", desa: "Dawung" },
  { gapoktan: "Tani Bersatu", namaKelompok: "Ngudi Santoso", desa: "Dawung" },
  { gapoktan: "Sari Jaya", namaKelompok: "Sambi Barat", desa: "Tanjungsari" },
  { gapoktan: "Sari Jaya", namaKelompok: "Sumendung", desa: "Tanjungsari" },
  { gapoktan: "Sari Jaya", namaKelompok: "Sri Tanjung", desa: "Tanjungsari" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Sambi I", desa: "Soco" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Sambi II", desa: "Soco" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Gondang I", desa: "Soco" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Gondang II", desa: "Soco" },
  { gapoktan: "Mustika Sari", namaKelompok: "Mitro Wono", desa: "Karanggupito" },
  { gapoktan: "Mustika Sari", namaKelompok: "Paket", desa: "Karanggupito" },
  { gapoktan: "Mustika Sari", namaKelompok: "Wahana Mandiri", desa: "Karanggupito" },
  { gapoktan: "Mustika Sari", namaKelompok: "Mardi Tani", desa: "Karanggupito" },
  { gapoktan: "Mustika Sari", namaKelompok: "Ngudi Rukun", desa: "Karanggupito" },
  { gapoktan: "Mustika Sari", namaKelompok: "Sumber Duren", desa: "Karanggupito" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Suko Makmur", desa: "Karangrejo" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Sri Rejeki", desa: "Karangrejo" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Tani Mulyo", desa: "Karangrejo" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Ngudi Rahayu", desa: "Karangrejo" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Sedyo Mulyo", desa: "Karangrejo" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Tani Makmur", desa: "Karangrejo" },
  { gapoktan: "Wira Usaha", namaKelompok: "Dewi Sri", desa: "Simo" },
  { gapoktan: "Wira Usaha", namaKelompok: "Wira Tani", desa: "Simo" },
  { gapoktan: "Wira Usaha", namaKelompok: "Tentrem Rahayu", desa: "Simo" },
  { gapoktan: "Wira Usaha", namaKelompok: "Rukun Mulyo", desa: "Simo" },
  { gapoktan: "Tunas Santoso", namaKelompok: "Sidodadi Mulyo", desa: "Ploso" },
  { gapoktan: "Tunas Santoso", namaKelompok: "Ngudi Subur", desa: "Ploso" },
  { gapoktan: "Tunas Santoso", namaKelompok: "Ngudi Mulyo", desa: "Ploso" },
  { gapoktan: "Tunas Santoso", namaKelompok: "Garuda Tani", desa: "Ploso" },
  { gapoktan: "Tunas Santoso", namaKelompok: "Tani Subur", desa: "Ploso" },
  { gapoktan: "Maju Utomo", namaKelompok: "Ngudi Makmur", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Ngudi Santoso", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Bina Tani", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Ngudi Rahayu", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Dewi Sri", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Mitra Tani", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Ngudi Sari", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Sri Rejeki", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Sumber Rejeki", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Tani Makmur", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Tani Rahayu", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Tani Bahagia", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Wono Makmur", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Sumber Makmur", desa: "Majasem" },
  { gapoktan: "Maju Utomo", namaKelompok: "Tani Rukun", desa: "Majasem" },
  { gapoktan: "Setia Karya", namaKelompok: "Sido Muncul", desa: "Kendal" },
  { gapoktan: "Setia Karya", namaKelompok: "Tunas Harapan", desa: "Kendal" },
  { gapoktan: "Setia Karya", namaKelompok: "Sri Widodo", desa: "Kendal" },
  { gapoktan: "Setia Karya", namaKelompok: "Maju Makmur", desa: "Kendal" },
  { gapoktan: "Setia Karya", namaKelompok: "Rukun Santoso", desa: "Kendal" },
  { gapoktan: "Setia Karya", namaKelompok: "Wahyu Sadoro", desa: "Kendal" },
  { gapoktan: "Setia Karya", namaKelompok: "Bangun Trisno", desa: "Kendal" },
  { gapoktan: "Setia Karya", namaKelompok: "Wono Makmur", desa: "Kendal" },
  { gapoktan: "Setia Karya", namaKelompok: "Jati Luhur", desa: "Kendal" },
  { gapoktan: "Sido Laju", namaKelompok: "Wijil Makmur", desa: "Sidorejo" },
  { gapoktan: "Sido Laju", namaKelompok: "Giat Mertani", desa: "Sidorejo" },
  { gapoktan: "Sido Laju", namaKelompok: "Intan Tani", desa: "Sidorejo" },
  { gapoktan: "Sido Laju", namaKelompok: "Sido Makmur", desa: "Sidorejo" },
  { gapoktan: "Sido Laju", namaKelompok: "Sri Rejeki", desa: "Sidorejo" },
  { gapoktan: "Sido Laju", namaKelompok: "Sri Santoso", desa: "Sidorejo" },
  { gapoktan: "Sumber Kencono", namaKelompok: "Sri Luhur II", desa: "Gayam" },
  { gapoktan: "Sumber Kencono", namaKelompok: "Sri Sedono", desa: "Gayam" },
  { gapoktan: "Sumber Kencono", namaKelompok: "Sri Luwih II", desa: "Gayam" },
  { gapoktan: "Sumber Kencono", namaKelompok: "Sri Luwih I", desa: "Gayam" },
  { gapoktan: "Mitra Tani", namaKelompok: "Rukun Tani", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Tani Bahagia", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Marsudi Tani", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Ngudi Rejeki I", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Ngudi Rahayu", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Karya Bakti", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Tani Semulur", desa: "Dadapan" },
  { gapoktan: "Amanah", namaKelompok: "Ngudi Luwih", desa: "Patalan" },
  { gapoktan: "Amanah", namaKelompok: "Ngudi Santoso", desa: "Patalan" },
  { gapoktan: "Amanah", namaKelompok: "Makmur Sewatu", desa: "Patalan" },
  { gapoktan: "Amanah", namaKelompok: "Tani Sejajar I", desa: "Patalan" },
  { gapoktan: "Amanah", namaKelompok: "Tani Sejajar II", desa: "Patalan" },
  { gapoktan: "Amanah", namaKelompok: "Jeruk Gulung", desa: "Patalan" },
  { gapoktan: "Amanah", namaKelompok: "Sepudak Makmur", desa: "Patalan" },
  { gapoktan: "Amanah", namaKelompok: "Tani Makmur", desa: "Patalan" },
  { gapoktan: "Amanah", namaKelompok: "Makmur Secangkring", desa: "Patalan" },
{ gapoktan: "Sumber Rejeki", namaKelompok: "Sido Dadi I", desa: "Keras Wetan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sido Dadi II", desa: "Keras Wetan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sumber Agung", desa: "Keras Wetan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sumber Rejeki", desa: "Keras Wetan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sido Rukun", desa: "Keras Wetan" },
  { gapoktan: "Margo Lestari", namaKelompok: "Bogo Tani", desa: "Keniten" },
  { gapoktan: "Margo Lestari", namaKelompok: "Ngegot Tani", desa: "Keniten" },
  { gapoktan: "Margo Lestari", namaKelompok: "Tani Abadi", desa: "Keniten" },
  { gapoktan: "Margo Lestari", namaKelompok: "Tani Murakapi", desa: "Keniten" },
  { gapoktan: "Margo Lestari", namaKelompok: "Mulyo Tani", desa: "Keniten" },
  { gapoktan: "Margo Lestari", namaKelompok: "Rukun Tani Tejo Makmur", desa: "Keniten" },
  { gapoktan: "Sedyo Mulyo", namaKelompok: "Karya Tani", desa: "Tambakromo" },
  { gapoktan: "Sedyo Mulyo", namaKelompok: "Sumber Rejeki", desa: "Tambakromo" },
  { gapoktan: "Sedyo Mulyo", namaKelompok: "Sumber Karya", desa: "Tambakromo" },
  { gapoktan: "Sedyo Mulyo", namaKelompok: "Sumber Makmur", desa: "Tambakromo" },
  { gapoktan: "Mitra Tani", namaKelompok: "Sri Rejeki", desa: "Tepas" },
  { gapoktan: "Mitra Tani", namaKelompok: "Sri Rahayu", desa: "Tepas" },
  { gapoktan: "Mitra Tani", namaKelompok: "Sari Rejeki", desa: "Tepas" },
  { gapoktan: "Mitra Tani", namaKelompok: "Rukun Tani", desa: "Tepas" },
  { gapoktan: "Mitra Tani", namaKelompok: "Satria Tani", desa: "Tepas" },
  { gapoktan: "Mitra Tani", namaKelompok: "Tani Makmur", desa: "Tepas" },
  { gapoktan: "Margo Lestari", namaKelompok: "Sejahtera", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Sri Sedhono", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Dewi Sri", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Sido Mulyo", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Rukun Makmur", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Margo Tani", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Sedyo Rukun", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Tunas Makmur", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Tani Makmur", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Karya Makmur", desa: "Geneng" },
  { gapoktan: "Tani Murakabi", namaKelompok: "Wonosobo", desa: "Sidorejo" },
  { gapoktan: "Tani Murakabi", namaKelompok: "Sido Rukun", desa: "Sidorejo" },
  { gapoktan: "Tani Murakabi", namaKelompok: "Mina Makmur", desa: "Sidorejo" },
  { gapoktan: "Tani Murakabi", namaKelompok: "Tani Makmur", desa: "Sidorejo" },
  { gapoktan: "Tani Murakabi", namaKelompok: "Tani Maju", desa: "Sidorejo" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Sri Rejeki", desa: "Baderan" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Sri Sedhono", desa: "Baderan" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Sri Lestari", desa: "Baderan" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Sri Mulyo", desa: "Baderan" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Sri Murakapi", desa: "Baderan" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Utomo", desa: "Klampisan" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Rukun", desa: "Klampisan" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Raharjo", desa: "Klampisan" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Mulyo", desa: "Klampisan" },
{ gapoktan: "Usaha Bersama", namaKelompok: "Sri Anom", desa: "Kasreman" },
  { gapoktan: "Usaha Bersama", namaKelompok: "Sri Sumber", desa: "Kasreman" },
  { gapoktan: "Usaha Bersama", namaKelompok: "Sri Tanjung", desa: "Kasreman" },
  { gapoktan: "Usaha Bersama", namaKelompok: "Sri Rejeki", desa: "Kasreman" },
  { gapoktan: "Usaha Bersama", namaKelompok: "Sri Mulyo", desa: "Kasreman" },
  { gapoktan: "Usaha Bersama", namaKelompok: "Sri Lestari", desa: "Kasreman" },
  { gapoktan: "Karya Makmur", namaKelompok: "Sumber Tani", desa: "Kersikan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Sumber Mulyo", desa: "Kersikan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Sumber Purwo", desa: "Kersikan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Sumber Padi", desa: "Kersikan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Sumber Makmur", desa: "Kersikan" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Sri Gunting", desa: "Dempel" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Hadi Rejeki I", desa: "Dempel" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Hadi Rejeki II", desa: "Dempel" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Nglencong Sari I", desa: "Dempel" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Nglencong Sari II", desa: "Dempel" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Nglencong Sari III", desa: "Dempel" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Sedia Rukun", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Kadang Tani", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Rukun Santoso", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Klitik Sari", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Mitra Tani", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Sambir Tani", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Sri Sedono", desa: "Klitik" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Galuh Tani", desa: "Kersoharjo" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Bandung Tani", desa: "Kersoharjo" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Kerso Tani I", desa: "Kersoharjo" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Kerso Tani II", desa: "Kersoharjo" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Bangun Tani", desa: "Kersoharjo" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Tani Unggul", desa: "Kersoharjo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Pelita Maju", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Lestari", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Randu Songo", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Widodo", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Santoso", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Dewi Sinto", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Dewi Sri", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Harapan", desa: "Randu Songo" },
  { gapoktan: "Tani Makmur", namaKelompok: "Widodaren", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Widya Tani", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Gelora Masa", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Rahayu", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Purnama Tani", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Ngesti Rahayu", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Loh Jinawi", desa: "Widodaren" },
{ gapoktan: "Mekar Sari", namaKelompok: "Tani Jaya", desa: "Simo" },
  { gapoktan: "Mekar Sari", namaKelompok: "Tani Agung", desa: "Simo" },
  { gapoktan: "Mekar Sari", namaKelompok: "Tani makmur", desa: "Simo" },
  { gapoktan: "Mekar Sari", namaKelompok: "Sri Kembang", desa: "Simo" },
  { gapoktan: "Rukun Rahayu", namaKelompok: "Rukun Widodo", desa: "Sumengko" },
  { gapoktan: "Rukun Rahayu", namaKelompok: "Rukun Makmur", desa: "Sumengko" },
  { gapoktan: "Rukun Rahayu", namaKelompok: "Wiro Tani", desa: "Sumengko" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Tirak Tani", desa: "Tirak" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Tani Rahayu", desa: "Tirak" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Sri Lestari", desa: "Tirak" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Madyo Tani", desa: "Tirak" },
  { gapoktan: "Sejahtera", namaKelompok: "Sri Mulyo", desa: "Purwosari" },
  { gapoktan: "Sejahtera", namaKelompok: "Tani Makmur", desa: "Purwosari" },
  { gapoktan: "Sejahtera", namaKelompok: "Sri Sedono", desa: "Purwosari" },
  { gapoktan: "Sejahtera", namaKelompok: "Sri Makmur", desa: "Purwosari" },
  { gapoktan: "Utomo", namaKelompok: "Sri Widodo", desa: "Jenangan" },
  { gapoktan: "Utomo", namaKelompok: "Sri Rahayu", desa: "Jenangan" },
  { gapoktan: "Utomo", namaKelompok: "Sri Utomo", desa: "Jenangan" },
  { gapoktan: "Baroka", namaKelompok: "Sido Mulyo", desa: "Pojok" },
  { gapoktan: "Baroka", namaKelompok: "Mitra Tani", desa: "Pojok" },
  { gapoktan: "Baroka", namaKelompok: "Tani Santoso", desa: "Pojok" },
  { gapoktan: "Murakapi", namaKelompok: "Dewi Sri", desa: "Dinden" },
  { gapoktan: "Murakapi", namaKelompok: "Tani Mulyo", desa: "Dinden" },
  { gapoktan: "Murakapi", namaKelompok: "Taruna Bakti", desa: "Dinden" },
  { gapoktan: "Pandan Arum", namaKelompok: "Sri Santoso", desa: "Kendung" },
  { gapoktan: "Pandan Arum", namaKelompok: "Sri Muncul", desa: "Kendung" },
  { gapoktan: "Pandan Arum", namaKelompok: "Tani Raharjo", desa: "Kendung" },
  { gapoktan: "Gandri Makmur", namaKelompok: "Sri Rejeki", desa: "Gandri" },
  { gapoktan: "Gandri Makmur", namaKelompok: "Mulyaning Bebrayan.", desa: "Gandri" },
  { gapoktan: "Gandri Makmur", namaKelompok: "Mugi Rahayu", desa: "Gandri" },
  { gapoktan: "Gandri Makmur", namaKelompok: "Jati Makmur", desa: "Gandri" },
  { gapoktan: "Gandri Makmur", namaKelompok: "Mangun Karyo", desa: "Gandri" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Sumber Tani", desa: "Sumber" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Sumber Mulyo", desa: "Sumber" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Sumber Agung", desa: "Sumber" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Budi Karya", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Nganti Makmur", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Ngudi Kamulyan", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Sri Mulyo", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Muji Rahayu", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Tani Bahagia", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Margo Mulyo", desa: "Babadan" },
  { gapoktan: "Krida Tani", namaKelompok: "Krida Jaya", desa: "Pohkonyal" },
  { gapoktan: "Krida Tani", namaKelompok: "Sempulur", desa: "Pohkonyal" },
  { gapoktan: "Krida Tani", namaKelompok: "Tani Makmur", desa: "Pohkonyal" },
  { gapoktan: "Krida Tani", namaKelompok: "Gemah Ripah", desa: "Pohkonyal" },
 { gapoktan: "Karya Tani", namaKelompok: "Rahayu", desa: "Paras" },
  { gapoktan: "Karya Tani", namaKelompok: "Dewi Murni", desa: "Paras" },
  { gapoktan: "Karya Tani", namaKelompok: "Dewi Sri", desa: "Paras" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Rukun Jaya", desa: "Pleset" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Agung Tani", desa: "Pleset" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Timbul Karya", desa: "Pleset" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Timbul Jaya", desa: "Pleset" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Karya Tani", desa: "Pleset" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Sumber Makmur", desa: "Pangkur" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Raharjo", desa: "Pangkur" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Tani Makmur", desa: "Pangkur" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Tani Mulyo", desa: "Pangkur" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Angesti Rahayu", desa: "Pangkur" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Rukun Tani", desa: "Pangkur" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Waruk Tani", desa: "Waruktengah" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Sumber Tani", desa: "Waruktengah" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Margo rejo", desa: "Waruktengah" },
  { gapoktan: "Tri Langgeng", namaKelompok: "Moro Seneng", desa: "Ngompro" },
  { gapoktan: "Tri Langgeng", namaKelompok: "Rukun Jaya", desa: "Ngompro" },
  { gapoktan: "Tri Langgeng", namaKelompok: "Sido Langgeng", desa: "Ngompro" },
  { gapoktan: "Tri Langgeng", namaKelompok: "Tunggal Roso", desa: "Ngompro" },
  { gapoktan: "Manunggal", namaKelompok: "Sri Lestari", desa: "Campurasri" },
  { gapoktan: "Manunggal", namaKelompok: "Sri Rahayu", desa: "Campurasri" },
  { gapoktan: "Manunggal", namaKelompok: "Sri Mukti", desa: "Campurasri" },
  { gapoktan: "Manunggal", namaKelompok: "Al Muttaqin", desa: "Campurasri" },
  { gapoktan: "Manunggal", namaKelompok: "Sri Sedono", desa: "Campurasri" },
  { gapoktan: "Tani Moderen", namaKelompok: "Sri Rejeki", desa: "Danguk" },
  { gapoktan: "Tani Moderen", namaKelompok: "Ngudi Rahayu", desa: "Danguk" },
  { gapoktan: "Tani Moderen", namaKelompok: "Tani Makmur", desa: "Danguk" },
  { gapoktan: "Tani Bahagia", namaKelompok: "Rukun Makmur", desa: "Gempol" },
  { gapoktan: "Tani Bahagia", namaKelompok: "Rukun Abadi", desa: "Gempol" },
  { gapoktan: "Tani Bahagia", namaKelompok: "Rukun Widodo", desa: "Gempol" },
  { gapoktan: "Tani Bahagia", namaKelompok: "Rukun Santoso", desa: "Gempol" },
{ gapoktan: "Anom Tani", namaKelompok: "Sumber Bakat", desa: "Ringinanom" },
  { gapoktan: "Anom Tani", namaKelompok: "Marsudi Tani", desa: "Ringinanom" },
  { gapoktan: "Anom Tani", namaKelompok: "Sri Lestari", desa: "Ringinanom" },
  { gapoktan: "Makmur", namaKelompok: "Guyup Rukun", desa: "Sembung" },
  { gapoktan: "Makmur", namaKelompok: "Tulodho", desa: "Sembung" },
  { gapoktan: "Makmur", namaKelompok: "Rahayu", desa: "Sembung" },
  { gapoktan: "Makmur", namaKelompok: "Utomo", desa: "Sembung" },
  { gapoktan: "Sido Makmur", namaKelompok: "Sri Tani", desa: "Sidorejo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Rukun Tani", desa: "Sidorejo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Rukun Makmur", desa: "Sidorejo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Margo Mulyo", desa: "Sidorejo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Rukun Mulyo", desa: "Sidorejo" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Sri Mulyo", desa: "Dungmiri" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Klanding Tani", desa: "Dungmiri" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Sri Eko Karyo", desa: "Dungmiri" },
  { gapoktan: "Sido Mukti", namaKelompok: "Sri Makmur", desa: "Brangol" },
  { gapoktan: "Sido Mukti", namaKelompok: "Tulodho", desa: "Brangol" },
  { gapoktan: "Sinar Prima", namaKelompok: "Tani Mulyo", desa: "Sidokerto" },
  { gapoktan: "Sinar Prima", namaKelompok: "Mugo Lestari", desa: "Sidokerto" },
  { gapoktan: "Sinar Prima", namaKelompok: "Sidodadi", desa: "Sidokerto" },
  { gapoktan: "Sinar Prima", namaKelompok: "Sri Jaya I", desa: "Sidokerto" },
  { gapoktan: "Sinar Prima", namaKelompok: "Sri Jaya II", desa: "Sidokerto" },
  { gapoktan: "Jati Karya", namaKelompok: "Mardi Tani I", desa: "Jatipuro" },
  { gapoktan: "Jati Karya", namaKelompok: "Mardi Tani II", desa: "Jatipuro" },
  { gapoktan: "Jati Karya", namaKelompok: "Tani Mulyo", desa: "Jatipuro" },
  { gapoktan: "Jati Karya", namaKelompok: "Baron Makmur", desa: "Jatipuro" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Mulyo", desa: "Puhti" },
  { gapoktan: "Tani Makmur", namaKelompok: "Marsudi Utomo", desa: "Puhti" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Madyo", desa: "Puhti" },
  { gapoktan: "Karya Makmur", namaKelompok: "Arto Moro", desa: "Sawo" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Subur", desa: "Sawo" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Makmur", desa: "Sawo" },
  { gapoktan: "Tani Makmur", namaKelompok: "Ngudi Utomo", desa: "Karangjati" },
  { gapoktan: "Tani Makmur", namaKelompok: "Ngudi Rahayu", desa: "Karangjati" },
  { gapoktan: "Tani Makmur", namaKelompok: "Marsudi Karyo", desa: "Karangjati" },
  { gapoktan: "Tani Makmur", namaKelompok: "Margo Tani I", desa: "Karangjati" },
  { gapoktan: "Tani Makmur", namaKelompok: "Margo Tani II", desa: "Karangjati" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Manunggal", desa: "Legundi" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Makmur", desa: "Legundi" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Maju", desa: "Legundi" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Mulyo", desa: "Legundi" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Mandiri", desa: "Legundi" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Makaryo", desa: "Legundi" },
{ gapoktan: "Sumber Mulyo", namaKelompok: "Rukun Tani I", desa: "Rejomulyo" },
  { gapoktan: "Sumber Mulyo", namaKelompok: "Rukun Tani II", desa: "Rejomulyo" },
  { gapoktan: "Sumber Mulyo", namaKelompok: "Rukun Tani III", desa: "Rejomulyo" },
  { gapoktan: "Sumber Mulyo", namaKelompok: "Sido Makmur I", desa: "Rejomulyo" },
  { gapoktan: "Sumber Mulyo", namaKelompok: "Sido Makmur II", desa: "Rejomulyo" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani I", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani II", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani III", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani IV", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani V", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani VI", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani VII", desa: "Rejuno" },
  { gapoktan: "Jaya Makmur", namaKelompok: "Mekar Tani", desa: "Ploso Lor" },
  { gapoktan: "Jaya Makmur", namaKelompok: "Sumber Rejeki", desa: "Ploso Lor" },
  { gapoktan: "Jaya Makmur", namaKelompok: "Tani Jaya", desa: "Ploso Lor" },
  { gapoktan: "Tani Asih", namaKelompok: "Sri Lestari 1", desa: "Legowetan" },
  { gapoktan: "Tani Asih", namaKelompok: "Sri Lestari II", desa: "Legowetan" },
  { gapoktan: "Tani Asih", namaKelompok: "Tani Mulyo", desa: "Legowetan" },
  { gapoktan: "Tani Asih", namaKelompok: "Bumi Lestari", desa: "Legowetan" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Tani Mulyo", desa: "Dero" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Murni", desa: "Dero" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Rukun Makmur", desa: "Dero" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Unggul Mulyo", desa: "Dero" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Sumber Abadi", desa: "Dero" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Rahayu", desa: "Krompol" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Manunggal", desa: "Krompol" },
  { gapoktan: "Tani Makmur", namaKelompok: "Rukun Mulyo", desa: "Krompol" },
  { gapoktan: "Tani Makmur", namaKelompok: "Satrio Mulyo", desa: "Krompol" },
  { gapoktan: "Tani Makmur", namaKelompok: "Maju Makmur", desa: "Krompol" },
  { gapoktan: "Mitra Panca Tani", namaKelompok: "Sinar Tani", desa: "Mojo" },
  { gapoktan: "Mitra Panca Tani", namaKelompok: "Rukun Makmur", desa: "Mojo" },
  { gapoktan: "Mitra Panca Tani", namaKelompok: "Cahaya Tani", desa: "Mojo" },
  { gapoktan: "Mitra Panca Tani", namaKelompok: "Sari Tani", desa: "Mojo" },
  { gapoktan: "Mitra Panca Tani", namaKelompok: "Kusuma Tani", desa: "Mojo" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sumber Tani", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Karya Tani", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sido Tani I", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sido Tani II", desa: "Sumberhening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Mulyo I", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Mulyo II", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Budi Karomah", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Karya Makmur", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sri Lestari", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Subur", desa: "Sumberbening" },
  { gapoktan: "Ngremboko Ngudi Mulyo", namaKelompok: "Ngremboko", desa: "Bringin" },
  { gapoktan: "Ngremboko Ngudi Mulyo", namaKelompok: "Ngudi Luhur", desa: "Bringin" },
  { gapoktan: "Ngremboko Ngudi Mulyo", namaKelompok: "Tani Mulyo", desa: "Bringin" },
  { gapoktan: "Dampit Manunggal", namaKelompok: "Ngudi Raharjo", desa: "Dampit" },
  { gapoktan: "Dampit Manunggal", namaKelompok: "Ngudi Karya", desa: "Dampit" },
  { gapoktan: "Dampit Manunggal", namaKelompok: "Rukun Tani", desa: "Dampit" },
  { gapoktan: "Tirto Mulyo", namaKelompok: "Karya Tani", desa: "Suruh" },
  { gapoktan: "Tirto Mulyo", namaKelompok: "Rukun Makmur", desa: "Suruh" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Gawerejo", desa: "Gandong" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Suko Makmur", desa: "Gandong" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Sri Rejeki", desa: "Gandong" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Gemah Ripah", desa: "Gandong" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Lohjinawi", desa: "Gandong" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Sidomulyo", desa: "Gandong" },
{ gapoktan: "Sermu Tani", namaKelompok: "Setyo Tani", desa: "Kenongorejo" },
  { gapoktan: "Sermu Tani", namaKelompok: "Kenongo Mulyo", desa: "Kenongorejo" },
  { gapoktan: "Sermu Tani", namaKelompok: "Sri Mulyo", desa: "Kenongorejo" },
  { gapoktan: "Sermu Tani", namaKelompok: "Sari Tani", desa: "Kenongorejo" },
  { gapoktan: "Sermu Tani", namaKelompok: "Sri Rejeki I", desa: "Kenongorejo" },
  { gapoktan: "Sermu Tani", namaKelompok: "Sri Murakabi I", desa: "Kenongorejo" },
  { gapoktan: "Sermu Tani", namaKelompok: "Maju Makmur", desa: "Kenongorejo" },
  { gapoktan: "Sermu Tani", namaKelompok: "Sri Murakabi II", desa: "Kenongorejo" },
  { gapoktan: "Sermu Tani", namaKelompok: "Sri Rejeki II", desa: "Kenongorejo" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Ngudi Makmur", desa: "Banjaransari" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sri Makmur", desa: "Banjaransari" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Ngudi Mulyo", desa: "Banjaransari" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Tani Mukti", desa: "Banjaransari" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Tani Makmur", desa: "Banjaransari" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Tani Rejeki", desa: "Banjaransari" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Tani Karya", desa: "Bendo" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Rukun Tani", desa: "Bendo" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Tani Makmur", desa: "Bendo" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Karya Tani", desa: "Bendo" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Jaya Tani", desa: "Bendo" },
  { gapoktan: "Harapan Massa", namaKelompok: "Sido Dadi", desa: "Tambakromo" },
  { gapoktan: "Harapan Massa", namaKelompok: "Tani Makmur", desa: "Tambakromo" },
  { gapoktan: "Harapan Massa", namaKelompok: "Kawan Tani", desa: "Tambakromo" },
  { gapoktan: "Harapan Massa", namaKelompok: "Tani Agung", desa: "Tambakromo" },
  { gapoktan: "Rukun Rahayu", namaKelompok: "Rukun Makmur", desa: "Tungkulrejo" },
  { gapoktan: "Rukun Rahayu", namaKelompok: "Rukun Mulyo", desa: "Tungkulrejo" },
  { gapoktan: "Rukun Rahayu", namaKelompok: "Rukun Lestari", desa: "Tungkulrejo" },
  { gapoktan: "Margo Utomo", namaKelompok: "Sido Makmur", desa: "Bintoyo" },
  { gapoktan: "Margo Utomo", namaKelompok: "Sido Mukti", desa: "Bintoyo" },
  { gapoktan: "Margo Utomo", namaKelompok: "Sido Subur", desa: "Bintoyo" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Makmur", desa: "Sukowiyono" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Bangun", desa: "Sukowiyono" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Mulyo", desa: "Sukowiyono" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Subur", desa: "Sukowiyono" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Agung", desa: "Sukowiyono" },
  { gapoktan: "Karya Tani", namaKelompok: "Tani Mumpuni", desa: "Munggut" },
  { gapoktan: "Karya Tani", namaKelompok: "Tani Mulyo", desa: "Munggut" },
  { gapoktan: "Karya Tani", namaKelompok: "Tani Rejeki", desa: "Munggut" },
  { gapoktan: "Karya Tani", namaKelompok: "Setya Tani", desa: "Munggut" },
  { gapoktan: "Karya Tani", namaKelompok: "Tani Utomo", desa: "Munggut" },
  { gapoktan: "Karya Tani", namaKelompok: "Tani Luhur", desa: "Munggut" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Manoto Tani", desa: "Pacing" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Karya Tani", desa: "Pacing" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Sumber Rejeki", desa: "Pacing" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Tani Makmur", desa: "Pacing" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Mulyo", desa: "Padas" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Jaya", desa: "Padas" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Harta", desa: "Padas" },
  { gapoktan: "Tani Mandiri", namaKelompok: "Krido Tani", desa: "Kedungprahu" },
  { gapoktan: "Tani Mandiri", namaKelompok: "Mendalan Baru", desa: "Kedungprahu" },
  { gapoktan: "Tani Mandiri", namaKelompok: "Tani Subur", desa: "Kedungprahu" },
  { gapoktan: "Tani Mandiri", namaKelompok: "Sumber Makmur", desa: "Kedungprahu" },
  { gapoktan: "Tani Mandiri", namaKelompok: "Tani Mulyo", desa: "Kedungprahu" },
  { gapoktan: "Tani Mandiri", namaKelompok: "Ngesti Rahayu", desa: "Kedungprahu" },
  { gapoktan: "Tani Mandiri", namaKelompok: "Remaja Makmur", desa: "Kedungprahu" },
  { gapoktan: "Tani Mandiri", namaKelompok: "Karya Tani", desa: "Kedungprahu" },
  { gapoktan: "Sambodo", namaKelompok: "Tani Makmur", desa: "Sambiroto" },
  { gapoktan: "Sambodo", namaKelompok: "Ngudi Makmur", desa: "Sambiroto" },
  { gapoktan: "Sambodo", namaKelompok: "Rukun Santoso", desa: "Sambiroto" },
  { gapoktan: "Sambodo", namaKelompok: "Melati", desa: "Sambiroto" },
 { gapoktan: "Ngudi Raharjo", namaKelompok: "Sumber Tani I", desa: "Kwadungan Lor" },
  { gapoktan: "Ngudi Raharjo", namaKelompok: "Sumber Tani II", desa: "Kwadungan Lor" },
  { gapoktan: "Ngudi Raharjo", namaKelompok: "Tani Subur", desa: "Kwadungan Lor" },
  { gapoktan: "Ngudi Raharjo", namaKelompok: "Dewi Sri", desa: "Kwadungan Lor" },
  { gapoktan: "Sumber Tani", namaKelompok: "Ngesti Sari", desa: "Jatirejo" },
  { gapoktan: "Sumber Tani", namaKelompok: "Kunang Jati", desa: "Jatirejo" },
  { gapoktan: "Sumber Tani", namaKelompok: "Puspo Warno", desa: "Jatirejo" },
  { gapoktan: "Sumber Tani", namaKelompok: "Sri Mulyo", desa: "Jatirejo" },
  { gapoktan: "Sumber Tani", namaKelompok: "Jati Sari", desa: "Jatirejo" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sumber Tani", desa: "Cangakan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Makmur", desa: "Cangakan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Subur", desa: "Cangakan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Pamardi Siwi", desa: "Cangakan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Marsudi Tani", desa: "Cangakan" },
  { gapoktan: "Rejeki Agung", namaKelompok: "Sri Sedono", desa: "Karangmalang" },
  { gapoktan: "Rejeki Agung", namaKelompok: "Karang Tani", desa: "Karangmalang" },
  { gapoktan: "Rejeki Agung", namaKelompok: "Tani Luhur", desa: "Karangmalang" },
  { gapoktan: "Rejeki Agung", namaKelompok: "Karya Tani", desa: "Karangmalang" },
  { gapoktan: "Rejeki Agung", namaKelompok: "Sri Rejeki", desa: "Karangmalang" },
  { gapoktan: "Tani Agung", namaKelompok: "Tani Mulyo", desa: "Kasreman" },
  { gapoktan: "Tani Agung", namaKelompok: "Tani Makmur", desa: "Kasreman" },
  { gapoktan: "Tani Agung", namaKelompok: "Tani Murni", desa: "Kasreman" },
  { gapoktan: "Tani Agung", namaKelompok: "Pucung Tani", desa: "Kasreman" },
  { gapoktan: "Tani Agung", namaKelompok: "Tarub Tani", desa: "Kasreman" },
  { gapoktan: "Tani Lancar", namaKelompok: "Sri Rejeki", desa: "Lego Kulon" },
  { gapoktan: "Tani Lancar", namaKelompok: "Sumber Makmur", desa: "Lego Kulon" },
  { gapoktan: "Tani Lancar", namaKelompok: "Gondang Sri", desa: "Lego Kulon" },
  { gapoktan: "Tani Lancar", namaKelompok: "Selo Sri", desa: "Lego Kulon" },
  { gapoktan: "Tani Makmur", namaKelompok: "Karya Remaja", desa: "Tawun" },
  { gapoktan: "Tani Makmur", namaKelompok: "Panorama", desa: "Tawun" },
  { gapoktan: "Tani Makmur", namaKelompok: "Mekarsari", desa: "Tawun" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tawun III", desa: "Tawun" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Subur", desa: "Tawun" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Widodo", desa: "Tawun" },
  { gapoktan: "Tani Makmur", namaKelompok: "Karya Asih", desa: "Tawun" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sidodadi", desa: "Tawun" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Subur Makmur", desa: "Kiyonten" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Pondok Tani", desa: "Kiyonten" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Karya Tani", desa: "Kiyonten" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Sri Rahayu", desa: "Kiyonten" },
  { gapoktan: "Tani Maju", namaKelompok: "Suka Maju", desa: "Gunungsari" },
  { gapoktan: "Tani Maju", namaKelompok: "Rejeki Tani", desa: "Gunungsari" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Makmur I", desa: "Gunungsari" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Makmur II", desa: "Gunungsari" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Subur", desa: "Gunungsari" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Mulyo", desa: "Gunungsari" },
  { gapoktan: "Mangun Tani", namaKelompok: "Nuju Makmur I", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Nuju Makmur II", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Karya Bakti I", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Karya Bakti II", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Karya Bakti III", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Sri Among Tani", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Sri Among Tani II", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Kardi Mulyo I", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Kardi Mulyo II", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Kardi Mulyo III", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Nuju Mulyo", desa: "Mangunharjo" },
  { gapoktan: "Mangun Tani", namaKelompok: "Nuju Adil", desa: "Mangunharjo" },
 { gapoktan: "Tani Mulyo", namaKelompok: "Sri Lestari", desa: "Kandangan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sri Lestari II", desa: "Kandangan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Ngudi Rahayu I", desa: "Kandangan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Ngudi Rahayu 2", desa: "Kandangan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sri Mulyo", desa: "Kandangan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sido Makmur", desa: "Kandangan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sido Makmur II", desa: "Kandangan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Karang Tani", desa: "Kandangan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Karang Makmur", desa: "Kandangan" },
  { gapoktan: "Tani Makmur", namaKelompok: "Rukun Tani", desa: "Kartoharjo" },
  { gapoktan: "Tani Makmur", namaKelompok: "Rukun Tani II", desa: "Kartoharjo" },
  { gapoktan: "Tani Makmur", namaKelompok: "Among Tani", desa: "Kartoharjo" },
  { gapoktan: "Tani Makmur", namaKelompok: "Pangkur Sari", desa: "Kartoharjo" },
  { gapoktan: "Tani Asih", namaKelompok: "Sri Tani", desa: "Beran" },
  { gapoktan: "Tani Asih", namaKelompok: "Tani Lestari", desa: "Beran" },
  { gapoktan: "Tani Asih", namaKelompok: "Ingasrejo I", desa: "Beran" },
  { gapoktan: "Tani Asih", namaKelompok: "Ingasrejo II", desa: "Beran" },
  { gapoktan: "Tani Asih", namaKelompok: "Berkah Tani", desa: "Beran" },
  { gapoktan: "Tani Asih", namaKelompok: "Sumber Makmur", desa: "Beran" },
  { gapoktan: "Tani Asih", namaKelompok: "Tani Mujur", desa: "Beran" },
  { gapoktan: "Mekarsari", namaKelompok: "Sarirejo", desa: "Jururejo" },
  { gapoktan: "Mekarsari", namaKelompok: "Among Tani", desa: "Jururejo" },
  { gapoktan: "Mekarsari", namaKelompok: "Madyoasri", desa: "Jururejo" },
  { gapoktan: "Mekarsari", namaKelompok: "Sri Rejeki I", desa: "Jururejo" },
  { gapoktan: "Mekarsari", namaKelompok: "Sri Rejeki II", desa: "Jururejo" },
  { gapoktan: "Tani Waras", namaKelompok: "Setyo Bhakti", desa: "Watualang" },
  { gapoktan: "Tani Waras", namaKelompok: "Sumber Makmur", desa: "Watualang" },
  { gapoktan: "Tani Waras", namaKelompok: "Setyo Bogo", desa: "Watualang" },
  { gapoktan: "Tani Waras", namaKelompok: "Setyo Budi", desa: "Watualang" },
  { gapoktan: "Tani Waras", namaKelompok: "Setyo Bumi", desa: "Watualang" },
  { gapoktan: "Tani Waras", namaKelompok: "Sumber Asih", desa: "Watualang" },
  { gapoktan: "Tani Waras", namaKelompok: "Madyo Asri", desa: "Watualang" },
  { gapoktan: "Tani Waras", namaKelompok: "Sumber Rejeki", desa: "Watualang" },
  { gapoktan: "Tani Waras", namaKelompok: "Tani Mulyo", desa: "Watualang" },
  { gapoktan: "Undosari", namaKelompok: "Sumber Makmur", desa: "Grudo" },
  { gapoktan: "Undosari", namaKelompok: "Tani Mulyo", desa: "Grudo" },
  { gapoktan: "Undosari", namaKelompok: "Karya Tani", desa: "Grudo" },
  { gapoktan: "Undosari", namaKelompok: "Tani Makmur I", desa: "Grudo" },
  { gapoktan: "Undosari", namaKelompok: "Tani Makmur II", desa: "Grudo" },
  { gapoktan: "Undosari", namaKelompok: "Bolo Karya Tani", desa: "Grudo" },
  { gapoktan: "Mulia Sejahtera", namaKelompok: "Mulia Sejahtera", desa: "Margomulyo" },
  { gapoktan: "Mulyo Asri", namaKelompok: "Sri Asih", desa: "Karangasri" },
  { gapoktan: "Mulyo Asri", namaKelompok: "Jaya Asri", desa: "Karangasri" },
  { gapoktan: "Mulyo Asri", namaKelompok: "Tani Soko", desa: "Karangasri" },
  { gapoktan: "Sri Mulyo", namaKelompok: "Kadang Tani", desa: "Ngawi" },
  { gapoktan: "Sri Mulyo", namaKelompok: "Sri Lestari", desa: "Ngawi" },
  { gapoktan: "Sri Mulyo", namaKelompok: "Sri Rahayu", desa: "Ngawi" },
  { gapoktan: "Karya Tani", namaKelompok: "Sri Rejeki", desa: "Krt. Prandon" },
  { gapoktan: "Karya Tani", namaKelompok: "Ngudi Rahayu", desa: "Krt. Prandon" },
  { gapoktan: "Karya Tani", namaKelompok: "Tani Makmur", desa: "Krt. Prandon" },
  { gapoktan: "Karya Tani", namaKelompok: "Rukun Tani", desa: "Krt. Prandon" },
  { gapoktan: "Karya Tani", namaKelompok: "Ngudi Mulyo", desa: "Krt. Prandon" },
  { gapoktan: "Karya Tani", namaKelompok: "Tani Mulyo", desa: "Krt. Prandon" },
  { gapoktan: "Karya Tani", namaKelompok: "Sumber Rejeki", desa: "Krt. Prandon" },
  { gapoktan: "Karya Tani", namaKelompok: "Guyup Rukun", desa: "Krt. Prandon" },
  { gapoktan: "Makmur Abadi", namaKelompok: "Tani Karya", desa: "Banyuurip" },
  { gapoktan: "Makmur Abadi", namaKelompok: "Sido Makmur", desa: "Banyuurip" },
  { gapoktan: "Makmur Abadi", namaKelompok: "Karang Tani", desa: "Banyuurip" },
  { gapoktan: "Jati Mulyo", namaKelompok: "Ngudi Mulyo", desa: "Kerek" },
  { gapoktan: "Jati Mulyo", namaKelompok: "Ngudi Rahayu", desa: "Kerek" },
  { gapoktan: "Jati Mulyo", namaKelompok: "Maju Karya", desa: "Kerek" },
  { gapoktan: "Margo Tani", namaKelompok: "Sri Bumi", desa: "Gentong" },
  { gapoktan: "Margo Tani", namaKelompok: "Sido Makmur", desa: "Gentong" },
  { gapoktan: "Margo Tani", namaKelompok: "Sri Rahayu", desa: "Gentong" },
  { gapoktan: "Margo Tani", namaKelompok: "Sempulur", desa: "Gentong" },
  { gapoktan: "Margo Tani", namaKelompok: "Sae", desa: "Gentong" },
  { gapoktan: "Margo Tani", namaKelompok: "Sri Katon", desa: "Gentong" },
  { gapoktan: "Sumber Tani", namaKelompok: "Tani Makmur", desa: "Babadan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Sri Sedono", desa: "Babadan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Wiro Bumi", desa: "Babadan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Murni", desa: "Babadan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Sri Rejeki", desa: "Babadan" },
  { gapoktan: "Kedung Tani", namaKelompok: "Mekar Sari", desa: "Kedungputri" },
  { gapoktan: "Kedung Tani", namaKelompok: "Rahayu", desa: "Kedungputri" },
  { gapoktan: "Kedung Tani", namaKelompok: "Kenongo", desa: "Kedungputri" },
  { gapoktan: "Kedung Tani", namaKelompok: "Tani Makmur", desa: "Kedungputri" },
  { gapoktan: "Kedung Tani", namaKelompok: "Karya Tani", desa: "Kedungputri" },
  { gapoktan: "Kedung Tani", namaKelompok: "Sinar Tani", desa: "Kedungputri" },
  { gapoktan: "Kedung Tani", namaKelompok: "Mawar", desa: "Kedungputri" },
  { gapoktan: "Kedung Tani", namaKelompok: "Margo Mulyo", desa: "Kedungputri" },
  { gapoktan: "Tani Rahayu", namaKelompok: "Sri Rejeki", desa: "Semen" },
  { gapoktan: "Tani Rahayu", namaKelompok: "Lestari", desa: "Semen" },
  { gapoktan: "Tani Rahayu", namaKelompok: "Mulyo Tani", desa: "Semen" },
  { gapoktan: "Tani Rahayu", namaKelompok: "Sri Mulyo", desa: "Semen" },
  { gapoktan: "Tani Rahayu", namaKelompok: "Rukun Tani", desa: "Semen" },
  { gapoktan: "Tani Rahayu", namaKelompok: "Karya Tani", desa: "Semen" },
  { gapoktan: "Teguh Tani", namaKelompok: "Sido Rukun", desa: "Teguhan" },
  { gapoktan: "Teguh Tani", namaKelompok: "Mardi Rahayu", desa: "Teguhan" },
  { gapoktan: "Teguh Tani", namaKelompok: "Ngudi Rahayu", desa: "Teguhan" },
  { gapoktan: "Teguh Tani", namaKelompok: "Sri Mulih", desa: "Teguhan" },
  { gapoktan: "Widodo Mulyo", namaKelompok: "Sri Asih", desa: "Sirigan" },
  { gapoktan: "Widodo Mulyo", namaKelompok: "Tani Mulyo", desa: "Sirigan" },
  { gapoktan: "Widodo Mulyo", namaKelompok: "Tani Mumpuni", desa: "Sirigan" },
  { gapoktan: "Bakti Tani", namaKelompok: "Sri Bhakti", desa: "Jeblogan" },
  { gapoktan: "Bakti Tani", namaKelompok: "Mardi Rahayu", desa: "Jeblogan" },
  { gapoktan: "Bakti Tani", namaKelompok: "Budi Luhur", desa: "Jeblogan" },
  { gapoktan: "Bakti Tani", namaKelompok: "Sri Mekar", desa: "Jeblogan" },
  { gapoktan: "Bakti Tani", namaKelompok: "Mekar Sari", desa: "Jeblogan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Tani Mulyo", desa: "Jambangan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Sri Makmur", desa: "Jambangan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Barokah", desa: "Jambangan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Sri Asih", desa: "Jambangan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Sri Rejeki", desa: "Jambangan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Margo Tani", desa: "Jambangan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Sumber Urip", desa: "Jambangan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Sri Widodo", desa: "Jambangan" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Jaya", desa: "Tempuran" },
  { gapoktan: "Tani Maju", namaKelompok: "Sumber Rejeki", desa: "Tempuran" },
  { gapoktan: "Tani Maju", namaKelompok: "Sido Makmur", desa: "Tempuran" },
  { gapoktan: "Tani Maju", namaKelompok: "Ngudi Utomo", desa: "Tempuran" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Rejo", desa: "Tempuran" },
  { gapoktan: "Tani Maju", namaKelompok: "Karya Tani", desa: "Tempuran" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Murni", desa: "Tempuran" },
  { gapoktan: "Tani Maju", namaKelompok: "Sri Mentes", desa: "Tempuran" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Langgeng", desa: "Tempuran" },
  { gapoktan: "Mitra Tani", namaKelompok: "Sidodadi", desa: "Dawu" },
  { gapoktan: "Mitra Tani", namaKelompok: "Sri Mekar", desa: "Dawu" },
  { gapoktan: "Mitra Tani", namaKelompok: "Tani Makmur", desa: "Dawu" },
  { gapoktan: "Karya Tani", namaKelompok: "Tani Subur", desa: "Paron" },
  { gapoktan: "Karya Tani", namaKelompok: "Tani Sentosa", desa: "Paron" },
  { gapoktan: "Karya Tani", namaKelompok: "Tani Bahagia", desa: "Paron" },
 { gapoktan: "Prima Tani", namaKelompok: "Sumber Bumi I", desa: "Gelung" },
  { gapoktan: "Prima Tani", namaKelompok: "Sumber Bumi II", desa: "Gelung" },
  { gapoktan: "Prima Tani", namaKelompok: "Sumber Rejeki I", desa: "Gelung" },
  { gapoktan: "Prima Tani", namaKelompok: "Sumber Rejeki II", desa: "Gelung" },
  { gapoktan: "Prima Tani", namaKelompok: "Tani Karya", desa: "Gelung" },
  { gapoktan: "Prima Tani", namaKelompok: "Muliya", desa: "Gelung" },
  { gapoktan: "Prima Tani", namaKelompok: "Sido Mekar", desa: "Gelung" },
  { gapoktan: "Guyub", namaKelompok: "Margo Rukun", desa: "Ngale" },
  { gapoktan: "Guyub", namaKelompok: "Sedyo Makmur", desa: "Ngale" },
  { gapoktan: "Guyub", namaKelompok: "Sedyo Rukun I", desa: "Ngale" },
  { gapoktan: "Guyub", namaKelompok: "Sedyo Rukun II", desa: "Ngale" },
  { gapoktan: "Guyub", namaKelompok: "Sedyo Rahayu", desa: "Ngale" },
  { gapoktan: "Guyub", namaKelompok: "Tani Subur I", desa: "Ngale" },
  { gapoktan: "Guyub", namaKelompok: "Tani Subur II", desa: "Ngale" },
  { gapoktan: "Guyub", namaKelompok: "Tani Mulyo", desa: "Ngale" },
  { gapoktan: "Rukun", namaKelompok: "Sri Utomo", desa: "Kebon" },
  { gapoktan: "Rukun", namaKelompok: "Tani Rukun", desa: "Kebon" },
  { gapoktan: "Rukun", namaKelompok: "Karya Tani", desa: "Kebon" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sedyo Rukun", desa: "Begal" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Mekar Sari", desa: "Begal" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Tempursari", desa: "Begal" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sri Sobo Siti", desa: "Begal" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Rahayu", desa: "Begal" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Bulak Sari", desa: "Begal" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Makmur", desa: "Begal" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Ngudi Santoso", desa: "Begal" },
  { gapoktan: "Wonorejo Lestari", namaKelompok: "Arco Mulyo", desa: "Wonorejo" },
  { gapoktan: "Wonorejo Lestari", namaKelompok: "Lestari I", desa: "Wonorejo" },
  { gapoktan: "Wonorejo Lestari", namaKelompok: "Lestari II", desa: "Wonorejo" },
  { gapoktan: "Wonorejo Lestari", namaKelompok: "Lestari III", desa: "Wonorejo" },
  { gapoktan: "Wonorejo Lestari", namaKelompok: "Brubahan", desa: "Wonorejo" },
  { gapoktan: "Sekar Tani", namaKelompok: "Ngudi Rahayu", desa: "Katikan" },
  { gapoktan: "Sekar Tani", namaKelompok: "Manggis", desa: "Katikan" },
  { gapoktan: "Sekar Tani", namaKelompok: "Bulak Rejo", desa: "Katikan" },
  { gapoktan: "Sekar Tani", namaKelompok: "Gebung Sari", desa: "Katikan" },
  { gapoktan: "Sekar Tani", namaKelompok: "Tawang Sari", desa: "Katikan" },
  { gapoktan: "Sekar Tani", namaKelompok: "Tirto Mulyo", desa: "Katikan" },
  { gapoktan: "Sekar Tani", namaKelompok: "Mekar Usaha", desa: "Katikan" },
  { gapoktan: "Sekar Tani", namaKelompok: "Tunas Harapan", desa: "Katikan" },
  { gapoktan: "Pelang Makmur", namaKelompok: "Mekar Sari I", desa: "Pelang Kidul" },
  { gapoktan: "Pelang Makmur", namaKelompok: "Mekar Sari II", desa: "Pelang Kidul" },
  { gapoktan: "Pelang Makmur", namaKelompok: "Pelang", desa: "Pelang Kidul" },
  { gapoktan: "Pelang Makmur", namaKelompok: "Mutiara", desa: "Pelang Kidul" },
  { gapoktan: "Pelang Makmur", namaKelompok: "Sumber Waras I", desa: "Pelang Kidul" },
  { gapoktan: "Pelang Makmur", namaKelompok: "Sumber Waras II", desa: "Pelang Kidul" },
  { gapoktan: "Pelang Makmur", namaKelompok: "Wates", desa: "Pelang Kidul" },
  { gapoktan: "Pelang Makmur", namaKelompok: "Ponjen", desa: "Pelang Kidul" },
  { gapoktan: "Garda Tani", namaKelompok: "Tani Manunggal", desa: "Kedunggalar" },
  { gapoktan: "Garda Tani", namaKelompok: "Tani Maju", desa: "Kedunggalar" },
  { gapoktan: "Garda Tani", namaKelompok: "Sumber Makmur", desa: "Kedunggalar" },
  { gapoktan: "Garda Tani", namaKelompok: "Margo Rahayu", desa: "Kedunggalar" },
  { gapoktan: "Garda Tani", namaKelompok: "Ngupoyo Boga", desa: "Kedunggalar" },
  { gapoktan: "Garda Tani", namaKelompok: "Muji Rahayu", desa: "Kedunggalar" },
  { gapoktan: "Garda Tani", namaKelompok: "Tani Mulyo", desa: "Kedunggalar" },
  { gapoktan: "Garda Tani", namaKelompok: "Sri Rahayu", desa: "Kedunggalar" },
  { gapoktan: "Garda Tani", namaKelompok: "Ngudi Makmur", desa: "Kedunggalar" },
  { gapoktan: "Garda Tani", namaKelompok: "Ngudi Mulyo", desa: "Kedunggalar" },
  { gapoktan: "Garda Tani", namaKelompok: "Tani Rukun", desa: "Kedunggalar" },
{ gapoktan: "Jati Manunggal", namaKelompok: "Tani Makmur", desa: "Jatigembol" },
  { gapoktan: "Jati Manunggal", namaKelompok: "Karya Makmur", desa: "Jatigembol" },
  { gapoktan: "Jati Manunggal", namaKelompok: "Pilang Sari", desa: "Jatigembol" },
  { gapoktan: "Jati Manunggal", namaKelompok: "Tani Mulyo", desa: "Jatigembol" },
  { gapoktan: "Jati Manunggal", namaKelompok: "Jatigembol", desa: "Jatigembol" },
  { gapoktan: "Jati Manunggal", namaKelompok: "Sri Mulyo", desa: "Jatigembol" },
  { gapoktan: "Jati Manunggal", namaKelompok: "Sri Karya", desa: "Jatigembol" },
  { gapoktan: "Jati Manunggal", namaKelompok: "Sri Rejeki", desa: "Jatigembol" },
  { gapoktan: "Surya Tani", namaKelompok: "Ngudi Lestari", desa: "Pelang Lor" },
  { gapoktan: "Surya Tani", namaKelompok: "Tambak Selo", desa: "Pelang Lor" },
  { gapoktan: "Surya Tani", namaKelompok: "Sumber Rejeki", desa: "Pelang Lor" },
  { gapoktan: "Surya Tani", namaKelompok: "Tani Mulyo", desa: "Pelang Lor" },
  { gapoktan: "Surya Tani", namaKelompok: "Soco Tani I", desa: "Pelang Lor" },
  { gapoktan: "Surya Tani", namaKelompok: "Soco Tani II", desa: "Pelang Lor" },
  { gapoktan: "Bangun Tani", namaKelompok: "Poh Jagal I", desa: "Bangunrejo Kidul" },
  { gapoktan: "Bangun Tani", namaKelompok: "Poh Jagal II", desa: "Bangunrejo Kidul" },
  { gapoktan: "Bangun Tani", namaKelompok: "Nuju Mulyo I", desa: "Bangunrejo Kidul" },
  { gapoktan: "Bangun Tani", namaKelompok: "Nuju Mulyo II", desa: "Bangunrejo Kidul" },
  { gapoktan: "Bangun Tani", namaKelompok: "Margo Makmur", desa: "Bangunrejo Kidul" },
  { gapoktan: "Bangun Tani", namaKelompok: "Ngudi Mulyo", desa: "Bangunrejo Kidul" },
  { gapoktan: "Bangun Tani", namaKelompok: "Blombangrejo", desa: "Bangunrejo Kidul" },
  { gapoktan: "Bangun Tani", namaKelompok: "Margo Utomo", desa: "Bangunrejo Kidul" },
  { gapoktan: "Bangun Tani", namaKelompok: "Alas Budi", desa: "Bangunrejo Kidul" },
  { gapoktan: "Bangun Tani", namaKelompok: "Golan Tani", desa: "Bangunrejo Kidul" },
  { gapoktan: "Sinar Hikmah", namaKelompok: "Sinar Tani", desa: "Jenggrik" },
  { gapoktan: "Sinar Hikmah", namaKelompok: "Sinar Jaya", desa: "Jenggrik" },
  { gapoktan: "Sinar Hikmah", namaKelompok: "Sinar Ratih", desa: "Jenggrik" },
  { gapoktan: "Sinar Hikmah", namaKelompok: "Sinar Wulan", desa: "Jenggrik" },
  { gapoktan: "Sinar Hikmah", namaKelompok: "Sinar Mulyo", desa: "Jenggrik" },
  { gapoktan: "Sinar Hikmah", namaKelompok: "Sinar Rejeki", desa: "Jenggrik" },
  { gapoktan: "Sinar Hikmah", namaKelompok: "Sinar Utama", desa: "Jenggrik" },
  { gapoktan: "Sinar Hikmah", namaKelompok: "Sinar Sri", desa: "Jenggrik" },
  { gapoktan: "Sinar Hikmah", namaKelompok: "Sinar Lestari", desa: "Jenggrik" },
  { gapoktan: "Rukun Tani", namaKelompok: "Jaya Murni", desa: "Wonokerto" },
  { gapoktan: "Rukun Tani", namaKelompok: "Sri Langgeng", desa: "Wonokerto" },
  { gapoktan: "Rukun Tani", namaKelompok: "Tani Mulyo", desa: "Wonokerto" },
  { gapoktan: "Rukun Tani", namaKelompok: "Sri Rejeki", desa: "Wonokerto" },
  { gapoktan: "Rukun Tani", namaKelompok: "Tani Jaya", desa: "Wonokerto" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Ngudi Mulyo I", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Sri Ngudi Lestari", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Mekar Sari", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Tani Mulyo", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Sri Rejeki", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Ngudi Mulyo II", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Sri Mulyo", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Sumber Rejeki", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Tani Rahayu", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Ngudi Raharjo", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Ngudi Makmur", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Ngudi Rahayu", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Ngudi Tani", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Sri Ponjen", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Sri Lestari", desa: "Gemarang" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Tani Maju", desa: "Gemarang" },
 { gapoktan: "Kawu Sejahtera", namaKelompok: "Ngudi Makmur", desa: "Kawu" },
  { gapoktan: "Kawu Sejahtera", namaKelompok: "Sri Makmur", desa: "Kawu" },
  { gapoktan: "Kawu Sejahtera", namaKelompok: "Tani Makmur", desa: "Kawu" },
  { gapoktan: "Kawu Sejahtera", namaKelompok: "Sri Rejeki", desa: "Kawu" },
  { gapoktan: "Kawu Sejahtera", namaKelompok: "Sri Asih", desa: "Kawu" },
  { gapoktan: "Kawu Sejahtera", namaKelompok: "Tani Mulyo", desa: "Kawu" },
  { gapoktan: "Kawu Sejahtera", namaKelompok: "Kartini", desa: "Kawu" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Rejeki", desa: "Banjarbanggi" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tirto Utomo", desa: "Banjarbanggi" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Lestari", desa: "Banjarbanggi" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Makmur", desa: "Banjarbanggi" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Rukun", desa: "Banjarbanggi" },
  { gapoktan: "Sejahtera", namaKelompok: "Sidodadi", desa: "Bangunrejo Lor" },
  { gapoktan: "Sejahtera", namaKelompok: "Sumber Urip", desa: "Bangunrejo Lor" },
  { gapoktan: "Sejahtera", namaKelompok: "Gawe Rukun", desa: "Bangunrejo Lor" },
  { gapoktan: "Sejahtera", namaKelompok: "Ngrandu", desa: "Bangunrejo Lor" },
  { gapoktan: "Sido Makmur", namaKelompok: "Ngudi Sejahtera", desa: "Karanggeneng" },
  { gapoktan: "Sido Makmur", namaKelompok: "Ngudi Luhur", desa: "Karanggeneng" },
  { gapoktan: "Sido Makmur", namaKelompok: "Ngudi Rejeki", desa: "Karanggeneng" },
  { gapoktan: "Sido Makmur", namaKelompok: "Ngudi Makmur", desa: "Karanggeneng" },
  { gapoktan: "Sumber Tani", namaKelompok: "Aneka Tani", desa: "Papungan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Tani Maju", desa: "Papungan" },
  { gapoktan: "Sumber Tani", namaKelompok: "Eko Tani", desa: "Papungan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Mulyo", desa: "Cantel" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sumber Makmur", desa: "Cantel" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sri Mulyo", desa: "Cantel" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Asih", desa: "Cantel" },
  { gapoktan: "Tani Maju", namaKelompok: "Lumbung Jaya", desa: "Ngancar" },
  { gapoktan: "Tani Maju", namaKelompok: "Bina Sejahtera", desa: "Ngancar" },
  { gapoktan: "Tani Maju", namaKelompok: "Sri Mukti", desa: "Ngancar" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Makmur", desa: "Ngancar" },
  { gapoktan: "Tani Maju", namaKelompok: "Mandiri", desa: "Ngancar" },
  { gapoktan: "Manunggal", namaKelompok: "Sumber Tani", desa: "Kalang" },
  { gapoktan: "Manunggal", namaKelompok: "Pojok Raharjo", desa: "Kalang" },
  { gapoktan: "Manunggal", namaKelompok: "Sumber Rejeki", desa: "Kalang" },
  { gapoktan: "Manunggal", namaKelompok: "Tani Makmur", desa: "Kalang" },
  { gapoktan: "Manunggal", namaKelompok: "Tani Baru", desa: "Kalang" },
  { gapoktan: "Lumayan", namaKelompok: "Seger Waras", desa: "Pitu" },
  { gapoktan: "Lumayan", namaKelompok: "Seger Waras I", desa: "Pitu" },
  { gapoktan: "Lumayan", namaKelompok: "Sri Rejeki", desa: "Pitu" },
  { gapoktan: "Lumayan", namaKelompok: "Karya Tani I", desa: "Pitu" },
  { gapoktan: "Lumayan", namaKelompok: "Karya Tani II", desa: "Pitu" },
  { gapoktan: "Lumayan", namaKelompok: "Tani Makmur", desa: "Pitu" },
  { gapoktan: "Lumayan", namaKelompok: "Gubug Mulyo", desa: "Pitu" },
  { gapoktan: "Bhakti Tani", namaKelompok: "Mardi Laras", desa: "Dumplengan" },
  { gapoktan: "Bhakti Tani", namaKelompok: "Sumber Makmur", desa: "Dumplengan" },
  { gapoktan: "Bhakti Tani", namaKelompok: "Suka Maju", desa: "Dumplengan" },
  { gapoktan: "Bhakti Tani", namaKelompok: "Karya Tani", desa: "Dumplengan" },
  { gapoktan: "Bhakti Tani", namaKelompok: "Karya Bhakti", desa: "Dumplengan" },
  { gapoktan: "Selo Makmur", namaKelompok: "Enggal Makmur", desa: "Selopuro" },
  { gapoktan: "Selo Makmur", namaKelompok: "Maju Mapan", desa: "Selopuro" },
  { gapoktan: "Selo Makmur", namaKelompok: "Sendang Rejeki", desa: "Selopuro" },
  { gapoktan: "Selo Makmur", namaKelompok: "Bantoro Asri", desa: "Selopuro" },
{ gapoktan: "Lestari Jaya", namaKelompok: "Mugi Rahayu", desa: "Banyubiru" },
  { gapoktan: "Lestari Jaya", namaKelompok: "Tani Rahayu", desa: "Banyubiru" },
  { gapoktan: "Lestari Jaya", namaKelompok: "Lestari", desa: "Banyubiru" },
  { gapoktan: "Lestari Jaya", namaKelompok: "Sumber Rejeki", desa: "Banyubiru" },
  { gapoktan: "Lestari Jaya", namaKelompok: "Jinawi", desa: "Banyubiru" },
  { gapoktan: "Mukti Rahayu", namaKelompok: "Sri Rejeki", desa: "Kedunggudel" },
  { gapoktan: "Mukti Rahayu", namaKelompok: "Tani Makmur", desa: "Kedunggudel" },
  { gapoktan: "Mukti Rahayu", namaKelompok: "Nglebaksari", desa: "Kedunggudel" },
  { gapoktan: "Mukti Rahayu", namaKelompok: "Rahayu", desa: "Kedunggudel" },
  { gapoktan: "Mukti Rahayu", namaKelompok: "Pangudi Luhur", desa: "Kedunggudel" },
  { gapoktan: "Tanjung Mulyo", namaKelompok: "Sri Rejeki", desa: "Kayutrejo" },
  { gapoktan: "Tanjung Mulyo", namaKelompok: "Sumber Kayut", desa: "Kayutrejo" },
  { gapoktan: "Tanjung Mulyo", namaKelompok: "Sido Makmur", desa: "Kayutrejo" },
  { gapoktan: "Tanjung Mulyo", namaKelompok: "Tani Mulyo", desa: "Kayutrejo" },
  { gapoktan: "Tanjung Mulyo", namaKelompok: "Sumber Mulyo", desa: "Kayutrejo" },
  { gapoktan: "Tanjung Mulyo", namaKelompok: "Bangun Mulyo", desa: "Kayutrejo" },
  { gapoktan: "Sekar Mulyo", namaKelompok: "Selo Madu", desa: "Sekaralas" },
  { gapoktan: "Sekar Mulyo", namaKelompok: "Sekar Sari", desa: "Sekaralas" },
  { gapoktan: "Sekar Mulyo", namaKelompok: "Dulangtani", desa: "Sekaralas" },
  { gapoktan: "Sekar Mulyo", namaKelompok: "Wadangsari", desa: "Sekaralas" },
  { gapoktan: "Sekar Mulyo", namaKelompok: "Sri Langgeng", desa: "Sekaralas" },
  { gapoktan: "Sekar Jaya", namaKelompok: "Bedegan Tani", desa: "Sekarputih" },
  { gapoktan: "Sekar Jaya", namaKelompok: "Sekar Tani", desa: "Sekarputih" },
  { gapoktan: "Sekar Jaya", namaKelompok: "Sri Rahayu", desa: "Sekarputih" },
  { gapoktan: "Sekar Jaya", namaKelompok: "Kenongo Mulyo", desa: "Sekarputih" },
  { gapoktan: "Sekar Jaya", namaKelompok: "Kebon Agung", desa: "Sekarputih" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Suko Tani", desa: "Sido Makmur" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Puntuk Tani", desa: "Sido Makmur" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Crawuk Tani", desa: "Sido Makmur" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Tani Kuncoro", desa: "Sido Makmur" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Kasih Tani", desa: "Sido Makmur" },
  { gapoktan: "Mekar Tani", namaKelompok: "Jenak Tani", desa: "Sidolaju" },
  { gapoktan: "Mekar Tani", namaKelompok: "Tani Mulyo", desa: "Sidolaju" },
  { gapoktan: "Mekar Tani", namaKelompok: "Sedyo Rukun", desa: "Sidolaju" },
  { gapoktan: "Mekar Tani", namaKelompok: "Sidorejo Tani", desa: "Sidolaju" },
  { gapoktan: "Mekar Tani", namaKelompok: "Kerjo Tani", desa: "Sidolaju" },
  { gapoktan: "Mekar Tani", namaKelompok: "Mloso Tani", desa: "Sidolaju" },
  { gapoktan: "Mekar Tani", namaKelompok: "Tanon Tani", desa: "Sidolaju" },
  { gapoktan: "Mekar Tani", namaKelompok: "Sido Tani", desa: "Sidolaju" },
  { gapoktan: "Mulyo Agung", namaKelompok: "Sido Rukun", desa: "Karangbanyu" },
  { gapoktan: "Mulyo Agung", namaKelompok: "Jatisari", desa: "Karangbanyu" },
  { gapoktan: "Mulyo Agung", namaKelompok: "Sumber Rejeki", desa: "Karangbanyu" },
  { gapoktan: "Mulyo Agung", namaKelompok: "Wonokerto", desa: "Karangbanyu" },
  { gapoktan: "Mulyo Agung", namaKelompok: "Margomulyo", desa: "Karangbanyu" },
  { gapoktan: "Mulyo Agung", namaKelompok: "Butuh Tani", desa: "Karangbanyu" },
  { gapoktan: "Mulyo Agung", namaKelompok: "Tretes Tani", desa: "Karangbanyu" },
  { gapoktan: "Rukun Makmur", namaKelompok: "Gebang Sari", desa: "Walikukun" },
  { gapoktan: "Rukun Makmur", namaKelompok: "Getas Sari", desa: "Walikukun" },
  { gapoktan: "Rukun Makmur", namaKelompok: "Sri Rejeki", desa: "Walikukun" },
  { gapoktan: "Rukun Makmur", namaKelompok: "Sri Widodo", desa: "Walikukun" },
  { gapoktan: "Tani Makmur", namaKelompok: "Bulung Sari", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Makmur", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Rejeki", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Gemah Ripah", desa: "Widodaren" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Pandan Sari", desa: "Gendingan" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Jaten Sari", desa: "Gendingan" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Sumber Rejeki", desa: "Gendingan" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Edi Peni", desa: "Gendingan" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Rejo Sari", desa: "Gendingan" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Kedung Sari", desa: "Gendingan" },
  { gapoktan: "Dirgosari", namaKelompok: "Among Kismo", desa: "Kauman" },
  { gapoktan: "Dirgosari", namaKelompok: "Dirgo Sari", desa: "Kauman" },
  { gapoktan: "Dirgosari", namaKelompok: "Sumber Makmur", desa: "Kauman" },
  { gapoktan: "Dirgosari", namaKelompok: "Tanjang Sari", desa: "Kauman" },
  { gapoktan: "Dirgosari", namaKelompok: "Gembung Sari", desa: "Kauman" },
 { gapoktan: "Ngudi Makmur", namaKelompok: "Sido Mulyo", desa: "Tambakboyo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Bulak Gadungan", desa: "Tambakboyo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Tempursari", desa: "Tambakboyo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Pondok", desa: "Tambakboyo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Kepohan", desa: "Tambakboyo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Murni", desa: "Tambakboyo" },
  { gapoktan: "Manunggal Sejati", namaKelompok: "Sidodadi", desa: "Pakah" },
  { gapoktan: "Manunggal Sejati", namaKelompok: "Tani Maju", desa: "Pakah" },
  { gapoktan: "Manunggal Sejati", namaKelompok: "Bondan Tani", desa: "Pakah" },
  { gapoktan: "Manunggal Sejati", namaKelompok: "Bangsri", desa: "Pakah" },
  { gapoktan: "Manunggal Sejati", namaKelompok: "Krawang", desa: "Pakah" },
  { gapoktan: "Manunggal Sejati", namaKelompok: "Margo Tresna", desa: "Pakah" },
  { gapoktan: "Manunggal Sejati", namaKelompok: "Jaya Mandiri", desa: "Pakah" },
  { gapoktan: "Manunggal Tani", namaKelompok: "Sumber Rejeki", desa: "Kedungharjo" },
  { gapoktan: "Manunggal Tani", namaKelompok: "Margo Rukun", desa: "Kedungharjo" },
  { gapoktan: "Manunggal Tani", namaKelompok: "Tani Mulyo", desa: "Kedungharjo" },
  { gapoktan: "Manunggal Tani", namaKelompok: "Losari", desa: "Kedungharjo" },
  { gapoktan: "Manunggal Tani", namaKelompok: "Margo Mulyo", desa: "Kedungharjo" },
  { gapoktan: "Manunggal Tani", namaKelompok: "Sendang Mulyo", desa: "Kedungharjo" },
  { gapoktan: "Mekar Sari", namaKelompok: "Tambak Sari I", desa: "Mantingan" },
  { gapoktan: "Mekar Sari", namaKelompok: "Tambak Sari II", desa: "Mantingan" },
  { gapoktan: "Mekar Sari", namaKelompok: "Sekar Sari I", desa: "Mantingan" },
  { gapoktan: "Mekar Sari", namaKelompok: "Sekar Sari II", desa: "Mantingan" },
  { gapoktan: "Mekar Sari", namaKelompok: "Ledok Sari I", desa: "Mantingan" },
  { gapoktan: "Mekar Sari", namaKelompok: "Ledok Sari II", desa: "Mantingan" },
  { gapoktan: "Mekar Sari", namaKelompok: "Sri Agung", desa: "Mantingan" },
  { gapoktan: "Mekar Sari", namaKelompok: "Sekar Gading I", desa: "Mantingan" },
  { gapoktan: "Mekar Sari", namaKelompok: "Sekar Gading II", desa: "Mantingan" },
  { gapoktan: "Mekar Sari", namaKelompok: "Ganggang Sari", desa: "Mantingan" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Kartika Mulya", desa: "Sambirejo" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Sari Tani", desa: "Sambirejo" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Dewi Sri", desa: "Sambirejo" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Teluk Tani", desa: "Sambirejo" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Karya Tani", desa: "Sambirejo" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Sri Gading", desa: "Sambirejo" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Amurat", desa: "Sambirejo" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Tani Makmur", desa: "Sambirejo" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Sambi Mulyo", desa: "Sambirejo" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Rejo Tani", desa: "Sambirejo" },
  { gapoktan: "Jadi Makmur", namaKelompok: "Pondok Gontor", desa: "Sambirejo" },
  { gapoktan: "Intan Tani", namaKelompok: "Sri Rejeki", desa: "Pengkol" },
  { gapoktan: "Intan Tani", namaKelompok: "Tunas Harapan", desa: "Pengkol" },
  { gapoktan: "Intan Tani", namaKelompok: "Tani Rukun", desa: "Pengkol" },
  { gapoktan: "Intan Tani", namaKelompok: "Margo Rukun", desa: "Pengkol" },
  { gapoktan: "Intan Tani", namaKelompok: "Margo Mulyo", desa: "Pengkol" },
  { gapoktan: "Intan Tani", namaKelompok: "Candi Tani", desa: "Pengkol" },
  { gapoktan: "Intan Tani", namaKelompok: "Sumber Rejeki", desa: "Pengkol" },
  { gapoktan: "Intan Tani", namaKelompok: "Subur Makmur", desa: "Pengkol" },
  { gapoktan: "Intan Tani", namaKelompok: "Candi Mulyo", desa: "Pengkol" },
{ gapoktan: "Mulyo Sari", namaKelompok: "Sri Rejeki", desa: "Jatimulyo" },
  { gapoktan: "Mulyo Sari", namaKelompok: "Sumber Sari", desa: "Jatimulyo" },
  { gapoktan: "Mulyo Sari", namaKelompok: "Tlogo Sari", desa: "Jatimulyo" },
  { gapoktan: "Mulyo Sari", namaKelompok: "Losari", desa: "Jatimulyo" },
  { gapoktan: "Sekar Tani", namaKelompok: "Sumber Rejeki", desa: "Sekarjati" },
  { gapoktan: "Sekar Tani", namaKelompok: "Sekar Putih", desa: "Sekarjati" },
  { gapoktan: "Sekar Tani", namaKelompok: "Bina Karya", desa: "Sekarjati" },
  { gapoktan: "Sekar Tani", namaKelompok: "Sumber Widodo", desa: "Sekarjati" },
  { gapoktan: "Bangun Rejeki", namaKelompok: "Sri Makmur", desa: "Bangunrejo" },
  { gapoktan: "Bangun Rejeki", namaKelompok: "Sri Widodo", desa: "Bangunrejo" },
  { gapoktan: "Bangun Rejeki", namaKelompok: "Sri Langgeng", desa: "Bangunrejo" },
  { gapoktan: "Bangun Rejeki", namaKelompok: "Sri Lestari", desa: "Bangunrejo" },
  { gapoktan: "Bangun Rejeki", namaKelompok: "Wonosari", desa: "Bangunrejo" },
  { gapoktan: "Sriwedari", namaKelompok: "Sri Rejeki", desa: "Sriwedari" },
  { gapoktan: "Sriwedari", namaKelompok: "Bedug Sari", desa: "Sriwedari" },
  { gapoktan: "Sriwedari", namaKelompok: "Sari Mulyo I", desa: "Sriwedari" },
  { gapoktan: "Sriwedari", namaKelompok: "Sari Mulyo II", desa: "Sriwedari" },
  { gapoktan: "Sriwedari", namaKelompok: "Candi Sari", desa: "Sriwedari" },
  { gapoktan: "Sriwedari", namaKelompok: "Mekar Sari", desa: "Sriwedari" },
  { gapoktan: "Ngudi Rejeki", namaKelompok: "Rukun Makmur", desa: "Mengger" },
  { gapoktan: "Ngudi Rejeki", namaKelompok: "Gugur Sari", desa: "Mengger" },
  { gapoktan: "Ngudi Rejeki", namaKelompok: "Sido Rukun", desa: "Mengger" },
  { gapoktan: "Ngudi Rejeki", namaKelompok: "Sumber Rejeki", desa: "Mengger" },
  { gapoktan: "Tani Maju", namaKelompok: "Sido Makmur", desa: "Pandean" },
  { gapoktan: "Tani Maju", namaKelompok: "Ngrebeng I", desa: "Pandean" },
  { gapoktan: "Tani Maju", namaKelompok: "Ngrebeng II", desa: "Pandean" },
  { gapoktan: "Tani Maju", namaKelompok: "Nglegok Sari", desa: "Pandean" },
  { gapoktan: "Tani Maju", namaKelompok: "Sido Dadi", desa: "Pandean" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Raharjo", desa: "Pandean" },
  { gapoktan: "Tani Maju", namaKelompok: "Tani Karya", desa: "Pandean" },
  { gapoktan: "Tani Maju", namaKelompok: "Sumber Makmur", desa: "Pandean" },
  { gapoktan: "Karanganyar Abadi", namaKelompok: "Sri Langgeng", desa: "Karanganyar" },
  { gapoktan: "Karanganyar Abadi", namaKelompok: "Karang Asri", desa: "Karanganyar" },
  { gapoktan: "Karanganyar Abadi", namaKelompok: "Sri Rejeki", desa: "Karanganyar" },
  { gapoktan: "Karanganyar Abadi", namaKelompok: "Sido Makmur", desa: "Karanganyar" },
  { gapoktan: "Karanganyar Abadi", namaKelompok: "Rahayu Widodo", desa: "Karanganyar" },
  { gapoktan: "Karanganyar Abadi", namaKelompok: "Sido Dadi", desa: "Karanganyar" },
  { gapoktan: "Karanganyar Abadi", namaKelompok: "Talok Tani", desa: "Karanganyar" },
  { gapoktan: "Tani Maju", namaKelompok: "Sri Lestari", desa: "Gembol" },
  { gapoktan: "Tani Maju", namaKelompok: "Sri Makmur", desa: "Gembol" },
  { gapoktan: "Tani Maju", namaKelompok: "Sempulur", desa: "Gembol" },
  { gapoktan: "Tani Maju", namaKelompok: "Sari Bumi", desa: "Gembol" },
  { gapoktan: "Tani Maju", namaKelompok: "Pilang Sari", desa: "Gembol" },
  { gapoktan: "Tani Maju", namaKelompok: "Sri Rahayu", desa: "Gembol" }
];

module.exports = data