const data = [
  { gapoktan: "Lumintu", namaKelompok: "Karya Makmur", desa: "Wonosari" },
  { gapoktan: "Lumintu", namaKelompok: "Tani Karya", desa: "Wonosari" },
  { gapoktan: "Lumintu", namaKelompok: "Tani Maju", desa: "Wonosari" },
  { gapoktan: "Tani Harapan", namaKelompok: "Sri Rahayu", desa: "Pandansari" },
  { gapoktan: "Tani Harapan", namaKelompok: "Sri Sadono", desa: "Pandansari" },
  { gapoktan: "Tani Harapan", namaKelompok: "SriMukti", desa: "Pandansari" },
  { gapoktan: "Tani Makmur", namaKelompok: "Marsudi Luhur", desa: "Girikerto" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sido Luhur", desa: "Girikerto" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sido Mukti", desa: "Girikerto" },
  { gapoktan: "Dewi Sri", namaKelompok: "Sri Jaya", desa: "Ngrendeng" },
  { gapoktan: "Dewi Sri", namaKelompok: "Sri Mulyo", desa: "Ngrendeng" },
  { gapoktan: "Dewi Sri", namaKelompok: "Sri Handayani", desa: "Ngrendeng" },
  { gapoktan: "Dewi Sri", namaKelompok: "Sri Rejeki", desa: "Ngrendeng" },
  { gapoktan: "Argo Makmur", namaKelompok: "Tani Mulyo", desa: "Hargosari" },
  { gapoktan: "Argo Makmur", namaKelompok: "Sumber Rejeki", desa: "Hargosari" },
  { gapoktan: "Argo Makmur", namaKelompok: "Sri Makmur", desa: "Hargosari" },
  { gapoktan: "Argo Makmur", namaKelompok: "Sri Rejeki", desa: "Hargosari" },
  { gapoktan: "Argo Makmur", namaKelompok: "Panca Karya", desa: "Hargosari" },
  { gapoktan: "Sinar Jaya", namaKelompok: "Tani Makmur", desa: "Pocol" },
  { gapoktan: "Sinar Jaya", namaKelompok: "Tani Mulyo", desa: "Pocol" },
  { gapoktan: "Sinar Jaya", namaKelompok: "Tani Rukun", desa: "Pocol" },
  { gapoktan: "Sinar Jaya", namaKelompok: "Tani Widodo", desa: "Pocol" },
  { gapoktan: "Gemilang", namaKelompok: "Sri Mulyo", desa: "Gendol" },
  { gapoktan: "Gemilang", namaKelompok: "Sri Mulyo 1", desa: "Gendol" },
  { gapoktan: "Gemilang", namaKelompok: "Sri Mulyo 2", desa: "Gendol" },
  { gapoktan: "Gemilang", namaKelompok: "Sri Rejeki", desa: "Gendol" },
  { gapoktan: "Lintang Sadane", namaKelompok: "Sumber Makmur", desa: "Sine" },
  { gapoktan: "Lintang Sadane", namaKelompok: "Sri Sadani", desa: "Sine" },
  { gapoktan: "Lintang Sadane", namaKelompok: "Sri Widodo", desa: "Sine" },
  { gapoktan: "Lintang Sadane", namaKelompok: "Sri Makmur", desa: "Sine" },
  { gapoktan: "Lintang Sadane", namaKelompok: "Tani mulyo", desa: "Sine" },
  { gapoktan: "Sumber Barokah", namaKelompok: "Sri Rejeki 1", desa: "Sumberejo" },
  { gapoktan: "Sumber Barokah", namaKelompok: "Sri Rejeki 2", desa: "Sumberejo" },
  { gapoktan: "Sumber Barokah", namaKelompok: "Sido Luhur", desa: "Sumberejo" },
  { gapoktan: "Sumber Barokah", namaKelompok: "Makmur Selalu", desa: "Sumberejo" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sido Rukun", desa: "Sumbersari" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Makmur", desa: "Sumbersari" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sri Widodo", desa: "Sumbersari" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Tentrem", desa: "Sumbersari" },
  { gapoktan: "Baroto", namaKelompok: "Sri Makmur", desa: "Kuniran" },
  { gapoktan: "Baroto", namaKelompok: "Sedyo Rahayu", desa: "Kuniran" },
  { gapoktan: "Baroto", namaKelompok: "Sri Rejeki", desa: "Kuniran" },
  { gapoktan: "Baroto", namaKelompok: "Sri Rahayu", desa: "Kuniran" },
  { gapoktan: "Baroto", namaKelompok: "Tani Mukti", desa: "Kuniran" },
  { gapoktan: "Karya Makmur", namaKelompok: "Darmo Martani", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Usaha Tani", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Harapan", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Bakti Rahayu", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Makmur Selalu", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Sejahtera", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Maju", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Makmur Tani", desa: "Tulakan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Tukul", desa: "Tulakan" },
  { gapoktan: "Andalas", namaKelompok: "Tentrem Rahayu", desa: "Ketanggung" },
  { gapoktan: "Andalas", namaKelompok: "Makmur Bertani", desa: "Ketanggung" },
  { gapoktan: "Andalas", namaKelompok: "Martani Mulyo", desa: "Ketanggung" },
  { gapoktan: "Catur Manunggal", namaKelompok: "Mardi Rahayu", desa: "Jagir" },
  { gapoktan: "Catur Manunggal", namaKelompok: "Tani Karya", desa: "Jagir" },
  { gapoktan: "Catur Manunggal", namaKelompok: "Sri Rejeki", desa: "Jagir" },
  { gapoktan: "Catur Manunggal", namaKelompok: "Sri Rahayu", desa: "Jagir" },
  { gapoktan: "Sinar Bahagia", namaKelompok: "Sri Makmur", desa: "Kauman" },
  { gapoktan: "Sinar Bahagia", namaKelompok: "Tani Subur", desa: "Kauman" },
  { gapoktan: "Sinar Bahagia", namaKelompok: "Tani Bahagia", desa: "Kauman" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Sri Makmur I", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Sri Makmur II", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Dadi Mulyo", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Hargo Makmur", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Sri Rahayu", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Hargo Lestari", desa: "Hargomulyo" },
  { gapoktan: "Lawu Makmur", namaKelompok: "Sido dadi", desa: "Hargomulyo" },
  { gapoktan: "Tani Lestari", namaKelompok: "Sido Makmur", desa: "Giriharjo" },
  { gapoktan: "Tani Lestari", namaKelompok: "Sido Rukun", desa: "Giriharjo" },
  { gapoktan: "Tani Lestari", namaKelompok: "Sido Mukti", desa: "Giriharjo" },
  { gapoktan: "Tani Lestari", namaKelompok: "Sido Maju", desa: "Giriharjo" },
  { gapoktan: "Tani Lestari", namaKelompok: "Giri Wono", desa: "Giriharjo" },
  { gapoktan: "Ngudi Roso", namaKelompok: "Tani Mulyo", desa: "Setono" },
  { gapoktan: "Ngudi Roso", namaKelompok: "Lawu Indah", desa: "Setono" },
  { gapoktan: "Ngudi Roso", namaKelompok: "Lawu Makmur", desa: "Setono" },
  { gapoktan: "Ngudi Roso", namaKelompok: "Sri Mulyo", desa: "Setono" },
  { gapoktan: "Ngudi Roso", namaKelompok: "Sri Sadono", desa: "Setono" },
  { gapoktan: "Margo Manunggal", namaKelompok: "Margo Rahayu", desa: "Wakah" },
  { gapoktan: "Margo Manunggal", namaKelompok: "Margo Rukun", desa: "Wakah" },
  { gapoktan: "Margo Manunggal", namaKelompok: "Gemah Ripah I", desa: "Wakah" },
  { gapoktan: "Margo Manunggal", namaKelompok: "Gemah Ripah II", desa: "Wakah" },
  { gapoktan: "Margo Manunggal", namaKelompok: "Sumber Rejeki", desa: "Wakah" },
  { gapoktan: "Manunggal Karso", namaKelompok: "Arum Dalu", desa: "Tawangrejo" },
  { gapoktan: "Manunggal Karso", namaKelompok: "Sri Rejeki", desa: "Tawangrejo" },
  { gapoktan: "Manunggal Karso", namaKelompok: "Sri Sadono", desa: "Tawangrejo" },
  { gapoktan: "Manunggal Karso", namaKelompok: "Tawang Sari", desa: "Tawangrejo" },
  { gapoktan: "Suka Mulya", namaKelompok: "Setia Kawan", desa: "Sambirejo" },
  { gapoktan: "Suka Mulya", namaKelompok: "Ngudi Tani", desa: "Sambirejo" },
  { gapoktan: "Suka Mulya", namaKelompok: "Margo Kencono", desa: "Sambirejo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Karya Tani", desa: "Manisharjo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Sri Mulih", desa: "Manisharjo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Konco Tani", desa: "Manisharjo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Karya Utama", desa: "Manisharjo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Ngudi Makmur", desa: "Manisharjo" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Subur Makmur", desa: "Manisharjo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Tirta Nirwala", desa: "Sidomulyo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Widu Satrio", desa: "Sidomulyo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Sadewo", desa: "Sidomulyo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Nakulo", desa: "Sidomulyo" },
  { gapoktan: "Sekar Lawu", namaKelompok: "Ngesti Rejeki", desa: "Ngrambe" },
  { gapoktan: "Sekar Lawu", namaKelompok: "Sempulur", desa: "Ngrambe" },
  { gapoktan: "Sekar Lawu", namaKelompok: "Ngesti Tani", desa: "Ngrambe" },
  { gapoktan: "Sekar Lawu", namaKelompok: "Ngesti Lestari", desa: "Ngrambe" },
  { gapoktan: "Sekar Lawu", namaKelompok: "Beran Makmur", desa: "Ngrambe" },
  { gapoktan: "Ardi Lawu", namaKelompok: "Sri Lestari", desa: "Babadan" },
  { gapoktan: "Ardi Lawu", namaKelompok: "Sri Widodo", desa: "Babadan" },
  { gapoktan: "Ardi Lawu", namaKelompok: "Sri Rejeki", desa: "Babadan" },
  { gapoktan: "Ardi Lawu", namaKelompok: "Mekar Tani", desa: "Babadan" },
  { gapoktan: "Ardi Lawu", namaKelompok: "Budi Luhur", desa: "Babadan" },
  { gapoktan: "Ngudi Tani", namaKelompok: "Sedyo Makmur", desa: "Krandegan" },
  { gapoktan: "Ngudi Tani", namaKelompok: "Kondang Makmur", desa: "Krandegan" },
  { gapoktan: "Ngudi Tani", namaKelompok: "Jati Lestari", desa: "Krandegan" },
  { gapoktan: "Ngudi Tani", namaKelompok: "Tani Makmur", desa: "Krandegan" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Tani Mulyo", desa: "Pucangan" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Among Tani", desa: "Pucangan" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Mekarsari", desa: "Pucangan" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Sri Rejeki", desa: "Pucangan" },
  { gapoktan: "Ngudi Makmur", namaKelompok: "Margo Rejeki", desa: "Pucangan" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Rejeki Tani", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Dewi Sri I", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Dewi Sri II", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Dewi Sri III", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Margo Mulyo", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Tani Mulyo", desa: "Cepoko" },
  { gapoktan: "Cepoko Mulya", namaKelompok: "Tani Manunggal", desa: "Cepoko" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Rukun Santoso II", desa: "Mendiro" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Rukun Santoso", desa: "Mendiro" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Ngudi Mulyo", desa: "Mendiro" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Suko Raharjo", desa: "Mendiro" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Sedyo Makmur 1", desa: "Mendiro" },
  { gapoktan: "Mandiro Harjo", namaKelompok: "Sedyo Makmur 2", desa: "Mendiro" },
  { gapoktan: "Umbul Mandiri", namaKelompok: "Sendang Kinasih", desa: "Umbulrejo" },
  { gapoktan: "Umbul Mandiri", namaKelompok: "Sendang Minulyo", desa: "Umbulrejo" },
  { gapoktan: "Mitra Tani", namaKelompok: "Pamardisiwi", desa: "Kletekan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Lawu Subur", desa: "Kletekan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Ngudi Rahayu", desa: "Kletekan" },
  { gapoktan: "Mitra Tani", namaKelompok: "Ngudi Utomo", desa: "Kletekan" },
  { gapoktan: "Jati Makmur", namaKelompok: "Arum Sari", desa: "Jaten" },
  { gapoktan: "Jati Makmur", namaKelompok: "Retno Mekar", desa: "Jaten" },
  { gapoktan: "Jati Makmur", namaKelompok: "Margo Tani", desa: "Jaten" },
  { gapoktan: "Jati Makmur", namaKelompok: "Citrun Jaya", desa: "Jaten" },
  { gapoktan: "Giri Bangkit", namaKelompok: "Rukun Tani", desa: "Girimulyo" },
  { gapoktan: "Giri Bangkit", namaKelompok: "Pamardi Tiwi", desa: "Girimulyo" },
  { gapoktan: "Giri Bangkit", namaKelompok: "Mulyo Rahayu", desa: "Girimulyo" },
  { gapoktan: "Giri Bangkit", namaKelompok: "Sido mulyo", desa: "Girimulyo" },
  { gapoktan: "Giri Bangkit", namaKelompok: "Sekar Asih", desa: "Girimulyo" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Budi Kamulyan", desa: "Ngrayudan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Jamandiri Kencana", desa: "Ngrayudan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sri Mulyo", desa: "Ngrayudan" },
  { gapoktan: "Tani Mulyo", namaKelompok: "Sri Widodo", desa: "Ngrayudan" },
  { gapoktan: "Garuda Merah", namaKelompok: "Sri Rejeki", desa: "Talang" },
  { gapoktan: "Garuda Merah", namaKelompok: "Sri Dadi", desa: "Talang" },
  { gapoktan: "Wahyu Risqi", namaKelompok: "Sri Asih", desa: "Macanan" },
  { gapoktan: "Wahyu Risqi", namaKelompok: "Pondok Makmur", desa: "Macanan" },
  { gapoktan: "Wahyu Risqi", namaKelompok: "Setyo Asih", desa: "Macanan" },
  { gapoktan: "Wahyu Risqi", namaKelompok: "Sendang Kamulyan", desa: "Macanan" },
  { gapoktan: "Sido Arum", namaKelompok: "Sido Makmur", desa: "Brubuh" },
  { gapoktan: "Sido Arum", namaKelompok: "Arum Dina", desa: "Brubuh" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Sido Makmur", desa: "Jogorogo" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Tani Subur", desa: "Jogorogo" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Tani Rahayu", desa: "Jogorogo" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Enggal Makmur", desa: "Jogorogo" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Sendang Makmur", desa: "Jogorogo" },
  { gapoktan: "Lawu Mulyo", namaKelompok: "Sekar Makmur", desa: "Jogorogo" },
  { gapoktan: "Tani Bersatu", namaKelompok: "Ngudi Mulyo", desa: "Dawung" },
  { gapoktan: "Tani Bersatu", namaKelompok: "Ngudi Rejeki", desa: "Dawung" },
  { gapoktan: "Tani Bersatu", namaKelompok: "Ngudi Rahayu", desa: "Dawung" },
  { gapoktan: "Tani Bersatu", namaKelompok: "Ngudi Santoso", desa: "Dawung" },
  { gapoktan: "Sari Jaya", namaKelompok: "Sambi Barat", desa: "Tanjungsari" },
  { gapoktan: "Sari Jaya", namaKelompok: "Sumendung", desa: "Tanjungsari" },
  { gapoktan: "Sari Jaya", namaKelompok: "Sri Tanjung", desa: "Tanjungsari" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Sambi I", desa: "Soco" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Sambi II", desa: "Soco" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Gondang I", desa: "Soco" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Gondang II", desa: "Soco" },
  { gapoktan: "Mustika Sari", namaKelompok: "Mitro Wono", desa: "Karanggupito" },
  { gapoktan: "Mustika Sari", namaKelompok: "Paket", desa: "Karanggupito" },
  { gapoktan: "Mustika Sari", namaKelompok: "Wahana Mandiri", desa: "Karanggupito" },
  { gapoktan: "Mustika Sari", namaKelompok: "Mardi Tani", desa: "Karanggupito" },
  { gapoktan: "Mustika Sari", namaKelompok: "Ngudi Rukun", desa: "Karanggupito" },
  { gapoktan: "Mustika Sari", namaKelompok: "Sumber Duren", desa: "Karanggupito" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Suko Makmur", desa: "Karangrejo" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Sri Rejeki", desa: "Karangrejo" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Tani Mulyo", desa: "Karangrejo" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Ngudi Rahayu", desa: "Karangrejo" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Sedyo Mulyo", desa: "Karangrejo" },
  { gapoktan: "Rejo Makmur", namaKelompok: "Tani Makmur", desa: "Karangrejo" },
  { gapoktan: "Wira Usaha", namaKelompok: "Dewi Sri", desa: "Simo" },
  { gapoktan: "Wira Usaha", namaKelompok: "Wira Tani", desa: "Simo" },
  { gapoktan: "Wira Usaha", namaKelompok: "Tentrem Rahayu", desa: "Simo" },
  { gapoktan: "Wira Usaha", namaKelompok: "Rukun Mulyo", desa: "Simo" },
  { gapoktan: "Tunas Santoso", namaKelompok: "Sidodadi Mulyo", desa: "Ploso" },
  { gapoktan: "Tunas Santoso", namaKelompok: "Ngudi Subur", desa: "Ploso" },
  { gapoktan: "Tunas Santoso", namaKelompok: "Ngudi Mulyo", desa: "Ploso" },
  { gapoktan: "Tunas Santoso", namaKelompok: "Garuda Tani", desa: "Ploso" },
  { gapoktan: "Tunas Santoso", namaKelompok: "Tani Subur", desa: "Ploso" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Ngudi Makmur", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Ngudi Santoso", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Bina Tani", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Ngudi Rahayu", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Dewi Sri", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Mitra Tani", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Ngudi Sari", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Sri Rejeki", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Sumber Rejeki", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Tani Makmur", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Tani Rahayu", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Tani Bahagia", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Wono Makmur", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Sumber Makmur", desa: "Majasem" },
  { gapoktan: "Maju Utomo", NamaKelompok: "Tani Rukun", desa: "Majasem" },
  { gapoktan: "Setia Karya", NamaKelompok: "Sido Muncul", desa: "Kendal" },
  { gapoktan: "Setia Karya", NamaKelompok: "Tunas Harapan", desa: "Kendal" },
  { gapoktan: "Setia Karya", NamaKelompok: "Sri Widodo", desa: "Kendal" },
  { gapoktan: "Setia Karya", NamaKelompok: "Maju Makmur", desa: "Kendal" },
  { gapoktan: "Setia Karya", NamaKelompok: "Rukun Santoso", desa: "Kendal" },
  { gapoktan: "Setia Karya", NamaKelompok: "Wahyu Sadoro", desa: "Kendal" },
  { gapoktan: "Setia Karya", NamaKelompok: "Bangun Trisno", desa: "Kendal" },
  { gapoktan: "Setia Karya", NamaKelompok: "Wono Makmur", desa: "Kendal" },
  { gapoktan: "Setia Karya", NamaKelompok: "Jati Luhur", desa: "Kendal" },
  { gapoktan: "Sido Laju", NamaKelompok: "Wijil Makmur", desa: "Sidorejo" },
  { gapoktan: "Sido Laju", NamaKelompok: "Giat Mertani", desa: "Sidorejo" },
  { gapoktan: "Sido Laju", NamaKelompok: "Intan Tani", desa: "Sidorejo" },
  { gapoktan: "Sido Laju", NamaKelompok: "Sido Makmur", desa: "Sidorejo" },
  { gapoktan: "Sido Laju", NamaKelompok: "Sri Rejeki", desa: "Sidorejo" },
  { gapoktan: "Sido Laju", NamaKelompok: "Sri Santoso", desa: "Sidorejo" },
  { gapoktan: "Sumber Kencono", NamaKelompok: "Sri Luhur II", desa: "Gayam" },
  { gapoktan: "Sumber Kencono", NamaKelompok: "Sri Sedono", desa: "Gayam" },
  { gapoktan: "Sumber Kencono", NamaKelompok: "Sri Luwih II", desa: "Gayam" },
  { gapoktan: "Sumber Kencono", NamaKelompok: "Sri Luwih I", desa: "Gayam" },
  { gapoktan: "Mitra Tani", NamaKelompok: "Rukun Tani", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", NamaKelompok: "Tani Bahagia", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", NamaKelompok: "Marsudi Tani", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", NamaKelompok: "Ngudi Rejeki I", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", NamaKelompok: "Ngudi Rahayu", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", NamaKelompok: "Karya Bakti", desa: "Dadapan" },
  { gapoktan: "Mitra Tani", NamaKelompok: "Tani Semulur", desa: "Dadapan" },
  { gapoktan: "Amanah", NamaKelompok: "Ngudi Luwih", desa: "Patalan" },
  { gapoktan: "Amanah", NamaKelompok: "Ngudi Santoso", desa: "Patalan" },
  { gapoktan: "Amanah", NamaKelompok: "Makmur Sewatu", desa: "Patalan" },
  { gapoktan: "Amanah", NamaKelompok: "Tani Sejajar I", desa: "Patalan" },
  { gapoktan: "Amanah", NamaKelompok: "Tani Sejajar II", desa: "Patalan" },
  { gapoktan: "Amanah", NamaKelompok: "Jeruk Gulung", desa: "Patalan" },
  { gapoktan: "Amanah", NamaKelompok: "Sepudak Makmur", desa: "Patalan" },
  { gapoktan: "Amanah", NamaKelompok: "Tani Makmur", desa: "Patalan" },
  { gapoktan: "Amanah", NamaKelompok: "Makmur Secangkring", desa: "Patalan" },
{ gapoktan: "Sumber Rejeki", namaKelompok: "Sido Dadi I", desa: "Keras Wetan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sido Dadi II", desa: "Keras Wetan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sumber Agung", desa: "Keras Wetan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sumber Rejeki", desa: "Keras Wetan" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sido Rukun", desa: "Keras Wetan" },
  { gapoktan: "Margo Lestari", namaKelompok: "Bogo Tani", desa: "Keniten" },
  { gapoktan: "Margo Lestari", namaKelompok: "Ngegot Tani", desa: "Keniten" },
  { gapoktan: "Margo Lestari", namaKelompok: "Tani Abadi", desa: "Keniten" },
  { gapoktan: "Margo Lestari", namaKelompok: "Tani Murakapi", desa: "Keniten" },
  { gapoktan: "Margo Lestari", namaKelompok: "Mulyo Tani", desa: "Keniten" },
  { gapoktan: "Margo Lestari", namaKelompok: "Rukun Tani Tejo Makmur", desa: "Keniten" },
  { gapoktan: "Sedyo Mulyo", namaKelompok: "Karya Tani", desa: "Tambakromo" },
  { gapoktan: "Sedyo Mulyo", namaKelompok: "Sumber Rejeki", desa: "Tambakromo" },
  { gapoktan: "Sedyo Mulyo", namaKelompok: "Sumber Karya", desa: "Tambakromo" },
  { gapoktan: "Sedyo Mulyo", namaKelompok: "Sumber Makmur", desa: "Tambakromo" },
  { gapoktan: "Mitra Tani", namaKelompok: "Sri Rejeki", desa: "Tepas" },
  { gapoktan: "Mitra Tani", namaKelompok: "Sri Rahayu", desa: "Tepas" },
  { gapoktan: "Mitra Tani", namaKelompok: "Sari Rejeki", desa: "Tepas" },
  { gapoktan: "Mitra Tani", namaKelompok: "Rukun Tani", desa: "Tepas" },
  { gapoktan: "Mitra Tani", namaKelompok: "Satria Tani", desa: "Tepas" },
  { gapoktan: "Mitra Tani", namaKelompok: "Tani Makmur", desa: "Tepas" },
  { gapoktan: "Margo Lestari", namaKelompok: "Sejahtera", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Sri Sedhono", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Dewi Sri", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Sido Mulyo", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Rukun Makmur", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Margo Tani", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Sedyo Rukun", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Tunas Makmur", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Tani Makmur", desa: "Geneng" },
  { gapoktan: "Margo Lestari", namaKelompok: "Karya Makmur", desa: "Geneng" },
  { gapoktan: "Tani Murakabi", namaKelompok: "Wonosobo", desa: "Sidorejo" },
  { gapoktan: "Tani Murakabi", namaKelompok: "Sido Rukun", desa: "Sidorejo" },
  { gapoktan: "Tani Murakabi", namaKelompok: "Mina Makmur", desa: "Sidorejo" },
  { gapoktan: "Tani Murakabi", namaKelompok: "Tani Makmur", desa: "Sidorejo" },
  { gapoktan: "Tani Murakabi", namaKelompok: "Tani Maju", desa: "Sidorejo" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Sri Rejeki", desa: "Baderan" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Sri Sedhono", desa: "Baderan" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Sri Lestari", desa: "Baderan" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Sri Mulyo", desa: "Baderan" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Sri Murakapi", desa: "Baderan" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Utomo", desa: "Klampisan" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Rukun", desa: "Klampisan" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Raharjo", desa: "Klampisan" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Mulyo", desa: "Klampisan" },
{ gapoktan: "Usaha Bersama", namaKelompok: "Sri Anom", desa: "Kasreman" },
  { gapoktan: "Usaha Bersama", namaKelompok: "Sri Sumber", desa: "Kasreman" },
  { gapoktan: "Usaha Bersama", namaKelompok: "Sri Tanjung", desa: "Kasreman" },
  { gapoktan: "Usaha Bersama", namaKelompok: "Sri Rejeki", desa: "Kasreman" },
  { gapoktan: "Usaha Bersama", namaKelompok: "Sri Mulyo", desa: "Kasreman" },
  { gapoktan: "Usaha Bersama", namaKelompok: "Sri Lestari", desa: "Kasreman" },
  { gapoktan: "Karya Makmur", namaKelompok: "Sumber Tani", desa: "Kersikan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Sumber Mulyo", desa: "Kersikan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Sumber Purwo", desa: "Kersikan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Sumber Padi", desa: "Kersikan" },
  { gapoktan: "Karya Makmur", namaKelompok: "Sumber Makmur", desa: "Kersikan" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Sri Gunting", desa: "Dempel" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Hadi Rejeki I", desa: "Dempel" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Hadi Rejeki II", desa: "Dempel" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Nglencong Sari I", desa: "Dempel" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Nglencong Sari II", desa: "Dempel" },
  { gapoktan: "Dempel Bangkit", namaKelompok: "Nglencong Sari III", desa: "Dempel" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Sedia Rukun", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Kadang Tani", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Rukun Santoso", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Klitik Sari", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Mitra Tani", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Sambir Tani", desa: "Klitik" },
  { gapoktan: "Subur Manunggal", namaKelompok: "Sri Sedono", desa: "Klitik" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Galuh Tani", desa: "Kersoharjo" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Bandung Tani", desa: "Kersoharjo" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Kerso Tani I", desa: "Kersoharjo" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Kerso Tani II", desa: "Kersoharjo" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Bangun Tani", desa: "Kersoharjo" },
  { gapoktan: "Mulyo Tani", namaKelompok: "Tani Unggul", desa: "Kersoharjo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Pelita Maju", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Lestari", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Randu Songo", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Widodo", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Santoso", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Dewi Sinto", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Dewi Sri", desa: "Randu Songo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Harapan", desa: "Randu Songo" },
  { gapoktan: "Tani Makmur", namaKelompok: "Widodaren", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Widya Tani", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Gelora Masa", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Rahayu", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Purnama Tani", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Ngesti Rahayu", desa: "Widodaren" },
  { gapoktan: "Tani Makmur", namaKelompok: "Loh Jinawi", desa: "Widodaren" },
{ gapoktan: "Mekar Sari", namaKelompok: "Tani Jaya", desa: "Simo" },
  { gapoktan: "Mekar Sari", namaKelompok: "Tani Agung", desa: "Simo" },
  { gapoktan: "Mekar Sari", namaKelompok: "Tani makmur", desa: "Simo" },
  { gapoktan: "Mekar Sari", namaKelompok: "Sri Kembang", desa: "Simo" },
  { gapoktan: "Rukun Rahayu", namaKelompok: "Rukun Widodo", desa: "Sumengko" },
  { gapoktan: "Rukun Rahayu", namaKelompok: "Rukun Makmur", desa: "Sumengko" },
  { gapoktan: "Rukun Rahayu", namaKelompok: "Wiro Tani", desa: "Sumengko" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Tirak Tani", desa: "Tirak" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Tani Rahayu", desa: "Tirak" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Sri Lestari", desa: "Tirak" },
  { gapoktan: "Guyub Rukun", namaKelompok: "Madyo Tani", desa: "Tirak" },
  { gapoktan: "Sejahtera", namaKelompok: "Sri Mulyo", desa: "Purwosari" },
  { gapoktan: "Sejahtera", namaKelompok: "Tani Makmur", desa: "Purwosari" },
  { gapoktan: "Sejahtera", namaKelompok: "Sri Sedono", desa: "Purwosari" },
  { gapoktan: "Sejahtera", namaKelompok: "Sri Makmur", desa: "Purwosari" },
  { gapoktan: "Utomo", namaKelompok: "Sri Widodo", desa: "Jenangan" },
  { gapoktan: "Utomo", namaKelompok: "Sri Rahayu", desa: "Jenangan" },
  { gapoktan: "Utomo", namaKelompok: "Sri Utomo", desa: "Jenangan" },
  { gapoktan: "Baroka", namaKelompok: "Sido Mulyo", desa: "Pojok" },
  { gapoktan: "Baroka", namaKelompok: "Mitra Tani", desa: "Pojok" },
  { gapoktan: "Baroka", namaKelompok: "Tani Santoso", desa: "Pojok" },
  { gapoktan: "Murakapi", namaKelompok: "Dewi Sri", desa: "Dinden" },
  { gapoktan: "Murakapi", namaKelompok: "Tani Mulyo", desa: "Dinden" },
  { gapoktan: "Murakapi", namaKelompok: "Taruna Bakti", desa: "Dinden" },
  { gapoktan: "Pandan Arum", namaKelompok: "Sri Santoso", desa: "Kendung" },
  { gapoktan: "Pandan Arum", namaKelompok: "Sri Muncul", desa: "Kendung" },
  { gapoktan: "Pandan Arum", namaKelompok: "Tani Raharjo", desa: "Kendung" },
  { gapoktan: "Gandri Makmur", namaKelompok: "Sri Rejeki", desa: "Gandri" },
  { gapoktan: "Gandri Makmur", namaKelompok: "Mulyaning Bebrayan.", desa: "Gandri" },
  { gapoktan: "Gandri Makmur", namaKelompok: "Mugi Rahayu", desa: "Gandri" },
  { gapoktan: "Gandri Makmur", namaKelompok: "Jati Makmur", desa: "Gandri" },
  { gapoktan: "Gandri Makmur", namaKelompok: "Mangun Karyo", desa: "Gandri" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Sumber Tani", desa: "Sumber" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Sumber Mulyo", desa: "Sumber" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Sumber Agung", desa: "Sumber" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Budi Karya", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Nganti Makmur", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Ngudi Kamulyan", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Sri Mulyo", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Muji Rahayu", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Tani Bahagia", desa: "Babadan" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Margo Mulyo", desa: "Babadan" },
  { gapoktan: "Krida Tani", namaKelompok: "Krida Jaya", desa: "Pohkonyal" },
  { gapoktan: "Krida Tani", namaKelompok: "Sempulur", desa: "Pohkonyal" },
  { gapoktan: "Krida Tani", namaKelompok: "Tani Makmur", desa: "Pohkonyal" },
  { gapoktan: "Krida Tani", namaKelompok: "Gemah Ripah", desa: "Pohkonyal" },
 { gapoktan: "Karya Tani", namaKelompok: "Rahayu", desa: "Paras" },
  { gapoktan: "Karya Tani", namaKelompok: "Dewi Murni", desa: "Paras" },
  { gapoktan: "Karya Tani", namaKelompok: "Dewi Sri", desa: "Paras" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Rukun Jaya", desa: "Pleset" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Agung Tani", desa: "Pleset" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Timbul Karya", desa: "Pleset" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Timbul Jaya", desa: "Pleset" },
  { gapoktan: "Sri Rejeki", namaKelompok: "Karya Tani", desa: "Pleset" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Sumber Makmur", desa: "Pangkur" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Raharjo", desa: "Pangkur" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Tani Makmur", desa: "Pangkur" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Tani Mulyo", desa: "Pangkur" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Angesti Rahayu", desa: "Pangkur" },
  { gapoktan: "Marsudi Tani", namaKelompok: "Rukun Tani", desa: "Pangkur" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Waruk Tani", desa: "Waruktengah" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Sumber Tani", desa: "Waruktengah" },
  { gapoktan: "Ngudi Barokah", namaKelompok: "Margo rejo", desa: "Waruktengah" },
  { gapoktan: "Tri Langgeng", namaKelompok: "Moro Seneng", desa: "Ngompro" },
  { gapoktan: "Tri Langgeng", namaKelompok: "Rukun Jaya", desa: "Ngompro" },
  { gapoktan: "Tri Langgeng", namaKelompok: "Sido Langgeng", desa: "Ngompro" },
  { gapoktan: "Tri Langgeng", namaKelompok: "Tunggal Roso", desa: "Ngompro" },
  { gapoktan: "Manunggal", namaKelompok: "Sri Lestari", desa: "Campurasri" },
  { gapoktan: "Manunggal", namaKelompok: "Sri Rahayu", desa: "Campurasri" },
  { gapoktan: "Manunggal", namaKelompok: "Sri Mukti", desa: "Campurasri" },
  { gapoktan: "Manunggal", namaKelompok: "Al Muttaqin", desa: "Campurasri" },
  { gapoktan: "Manunggal", namaKelompok: "Sri Sedono", desa: "Campurasri" },
  { gapoktan: "Tani Moderen", namaKelompok: "Sri Rejeki", desa: "Danguk" },
  { gapoktan: "Tani Moderen", namaKelompok: "Ngudi Rahayu", desa: "Danguk" },
  { gapoktan: "Tani Moderen", namaKelompok: "Tani Makmur", desa: "Danguk" },
  { gapoktan: "Tani Bahagia", namaKelompok: "Rukun Makmur", desa: "Gempol" },
  { gapoktan: "Tani Bahagia", namaKelompok: "Rukun Abadi", desa: "Gempol" },
  { gapoktan: "Tani Bahagia", namaKelompok: "Rukun Widodo", desa: "Gempol" },
  { gapoktan: "Tani Bahagia", namaKelompok: "Rukun Santoso", desa: "Gempol" },
{ gapoktan: "Anom Tani", namaKelompok: "Sumber Bakat", desa: "Ringinanom" },
  { gapoktan: "Anom Tani", namaKelompok: "Marsudi Tani", desa: "Ringinanom" },
  { gapoktan: "Anom Tani", namaKelompok: "Sri Lestari", desa: "Ringinanom" },
  { gapoktan: "Makmur", namaKelompok: "Guyup Rukun", desa: "Sembung" },
  { gapoktan: "Makmur", namaKelompok: "Tulodho", desa: "Sembung" },
  { gapoktan: "Makmur", namaKelompok: "Rahayu", desa: "Sembung" },
  { gapoktan: "Makmur", namaKelompok: "Utomo", desa: "Sembung" },
  { gapoktan: "Sido Makmur", namaKelompok: "Sri Tani", desa: "Sidorejo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Rukun Tani", desa: "Sidorejo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Rukun Makmur", desa: "Sidorejo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Margo Mulyo", desa: "Sidorejo" },
  { gapoktan: "Sido Makmur", namaKelompok: "Rukun Mulyo", desa: "Sidorejo" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Sri Mulyo", desa: "Dungmiri" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Klanding Tani", desa: "Dungmiri" },
  { gapoktan: "Rukun Jaya", namaKelompok: "Sri Eko Karyo", desa: "Dungmiri" },
  { gapoktan: "Sido Mukti", namaKelompok: "Sri Makmur", desa: "Brangol" },
  { gapoktan: "Sido Mukti", namaKelompok: "Tulodho", desa: "Brangol" },
  { gapoktan: "Sinar Prima", namaKelompok: "Tani Mulyo", desa: "Sidokerto" },
  { gapoktan: "Sinar Prima", namaKelompok: "Mugo Lestari", desa: "Sidokerto" },
  { gapoktan: "Sinar Prima", namaKelompok: "Sidodadi", desa: "Sidokerto" },
  { gapoktan: "Sinar Prima", namaKelompok: "Sri Jaya I", desa: "Sidokerto" },
  { gapoktan: "Sinar Prima", namaKelompok: "Sri Jaya II", desa: "Sidokerto" },
  { gapoktan: "Jati Karya", namaKelompok: "Mardi Tani I", desa: "Jatipuro" },
  { gapoktan: "Jati Karya", namaKelompok: "Mardi Tani II", desa: "Jatipuro" },
  { gapoktan: "Jati Karya", namaKelompok: "Tani Mulyo", desa: "Jatipuro" },
  { gapoktan: "Jati Karya", namaKelompok: "Baron Makmur", desa: "Jatipuro" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Mulyo", desa: "Puhti" },
  { gapoktan: "Tani Makmur", namaKelompok: "Marsudi Utomo", desa: "Puhti" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Madyo", desa: "Puhti" },
  { gapoktan: "Karya Makmur", namaKelompok: "Arto Moro", desa: "Sawo" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Subur", desa: "Sawo" },
  { gapoktan: "Karya Makmur", namaKelompok: "Tani Makmur", desa: "Sawo" },
  { gapoktan: "Tani Makmur", namaKelompok: "Ngudi Utomo", desa: "Karangjati" },
  { gapoktan: "Tani Makmur", namaKelompok: "Ngudi Rahayu", desa: "Karangjati" },
  { gapoktan: "Tani Makmur", namaKelompok: "Marsudi Karyo", desa: "Karangjati" },
  { gapoktan: "Tani Makmur", namaKelompok: "Margo Tani I", desa: "Karangjati" },
  { gapoktan: "Tani Makmur", namaKelompok: "Margo Tani II", desa: "Karangjati" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Manunggal", desa: "Legundi" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Makmur", desa: "Legundi" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Maju", desa: "Legundi" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Mulyo", desa: "Legundi" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Mandiri", desa: "Legundi" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Makaryo", desa: "Legundi" },
{ gapoktan: "Sumber Mulyo", namaKelompok: "Rukun Tani I", desa: "Rejomulyo" },
  { gapoktan: "Sumber Mulyo", namaKelompok: "Rukun Tani II", desa: "Rejomulyo" },
  { gapoktan: "Sumber Mulyo", namaKelompok: "Rukun Tani III", desa: "Rejomulyo" },
  { gapoktan: "Sumber Mulyo", namaKelompok: "Sido Makmur I", desa: "Rejomulyo" },
  { gapoktan: "Sumber Mulyo", namaKelompok: "Sido Makmur II", desa: "Rejomulyo" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani I", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani II", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani III", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani IV", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani V", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani VI", desa: "Rejuno" },
  { gapoktan: "Sapta Manunggal", namaKelompok: "Among Tani VII", desa: "Rejuno" },
  { gapoktan: "Jaya Makmur", namaKelompok: "Mekar Tani", desa: "Ploso Lor" },
  { gapoktan: "Jaya Makmur", namaKelompok: "Sumber Rejeki", desa: "Ploso Lor" },
  { gapoktan: "Jaya Makmur", namaKelompok: "Tani Jaya", desa: "Ploso Lor" },
  { gapoktan: "Tani Asih", namaKelompok: "Sri Lestari 1", desa: "Legowetan" },
  { gapoktan: "Tani Asih", namaKelompok: "Sri Lestari II", desa: "Legowetan" },
  { gapoktan: "Tani Asih", namaKelompok: "Tani Mulyo", desa: "Legowetan" },
  { gapoktan: "Tani Asih", namaKelompok: "Bumi Lestari", desa: "Legowetan" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Tani Mulyo", desa: "Dero" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Murni", desa: "Dero" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Rukun Makmur", desa: "Dero" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Unggul Mulyo", desa: "Dero" },
  { gapoktan: "Sumber Makmur", namaKelompok: "Sumber Abadi", desa: "Dero" },
  { gapoktan: "Tani Makmur", namaKelompok: "Sri Rahayu", desa: "Krompol" },
  { gapoktan: "Tani Makmur", namaKelompok: "Tani Manunggal", desa: "Krompol" },
  { gapoktan: "Tani Makmur", namaKelompok: "Rukun Mulyo", desa: "Krompol" },
  { gapoktan: "Tani Makmur", namaKelompok: "Satrio Mulyo", desa: "Krompol" },
  { gapoktan: "Tani Makmur", namaKelompok: "Maju Makmur", desa: "Krompol" },
  { gapoktan: "Mitra Panca Tani", namaKelompok: "Sinar Tani", desa: "Mojo" },
  { gapoktan: "Mitra Panca Tani", namaKelompok: "Rukun Makmur", desa: "Mojo" },
  { gapoktan: "Mitra Panca Tani", namaKelompok: "Cahaya Tani", desa: "Mojo" },
  { gapoktan: "Mitra Panca Tani", namaKelompok: "Sari Tani", desa: "Mojo" },
  { gapoktan: "Mitra Panca Tani", namaKelompok: "Kusuma Tani", desa: "Mojo" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sumber Tani", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Karya Tani", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sido Tani I", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sido Tani II", desa: "Sumberhening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Mulyo I", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Tani Mulyo II", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Budi Karomah", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Karya Makmur", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Sri Lestari", desa: "Sumberbening" },
  { gapoktan: "Sumber Rejeki", namaKelompok: "Subur", desa: "Sumberbening" },
  { gapoktan: "Ngremboko Ngudi Mulyo", namaKelompok: "Ngremboko", desa: "Bringin" },
  { gapoktan: "Ngremboko Ngudi Mulyo", namaKelompok: "Ngudi Luhur", desa: "Bringin" },
  { gapoktan: "Ngremboko Ngudi Mulyo", namaKelompok: "Tani Mulyo", desa: "Bringin" },
  { gapoktan: "Dampit Manunggal", namaKelompok: "Ngudi Raharjo", desa: "Dampit" },
  { gapoktan: "Dampit Manunggal", namaKelompok: "Ngudi Karya", desa: "Dampit" },
  { gapoktan: "Dampit Manunggal", namaKelompok: "Rukun Tani", desa: "Dampit" },
  { gapoktan: "Tirto Mulyo", namaKelompok: "Karya Tani", desa: "Suruh" },
  { gapoktan: "Tirto Mulyo", namaKelompok: "Rukun Makmur", desa: "Suruh" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Gawerejo", desa: "Gandong" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Suko Makmur", desa: "Gandong" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Sri Rejeki", desa: "Gandong" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Gemah Ripah", desa: "Gandong" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Lohjinawi", desa: "Gandong" },
  { gapoktan: "Manunggal Karya", namaKelompok: "Sidomulyo", desa: "Gandong" },
];
